// Généré à partir de l'extraction LPPR chapitre 7 (Orthoprothèses), arrêté du 3 novembre 2025.
// Ne pas éditer les codes/tarifs à la main : toute correction doit repartir du texte officiel.

export type LPPRProtheseItem = {
  code: string;
  nomenclature: string;
  tarifTTC: number;
  membre: "inferieur" | "superieur";
  famille: string;
  sousFamille?: string;
  source: string;
};

const SOURCE_LPPR = "Chapitre 7 LPPR (Titre II)";

export const lpprProtheseItems: LPPRProtheseItem[] = [
  {
    code: "2738081",
    nomenclature: "Genou monoaxial, régulation hydraulique de la phase pendulaire à accumulation d'énergie, contrôle du pied, composite carbone.",
    tarifTTC: 852.33,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "monoaxial",
    source: SOURCE_LPPR,
  },
  {
    code: "2770877",
    nomenclature: "Genou monoaxial, régulation pneumatique assistée par microprocesseur, composite carbone, frein mécanique, amortissement à l'attaque du pas (P < 120 kg).",
    tarifTTC: 4834.98,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "monoaxial",
    source: SOURCE_LPPR,
  },
  {
    code: "2736389",
    nomenclature: "Genou monoaxial, régulation pneumatique assistée par microprocesseur, composite carbone (P < 120 kg).",
    tarifTTC: 3413.67,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "monoaxial",
    source: SOURCE_LPPR,
  },
  {
    code: "2719340",
    nomenclature: "Genou monoaxial, régulation pneumatique assistée par microprocesseur, composite carbone, frein mécanique.",
    tarifTTC: 4644.27,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "monoaxial",
    source: SOURCE_LPPR,
  },
  {
    code: "2772480",
    nomenclature: "Genou monoaxial à frein stabilisateur.",
    tarifTTC: 35.49,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "monoaxial",
    source: SOURCE_LPPR,
  },
  {
    code: "2745075",
    nomenclature: "Genou monoaxial, régulation pneumatique, composite carbone, frein mécanique, amortissement à l'attaque du pas (P < 120 kg).",
    tarifTTC: 2363.83,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "monoaxial",
    source: SOURCE_LPPR,
  },
  {
    code: "2789664",
    nomenclature: "Genou monoaxial, régulation hydraulique, composite carbone, frein mécanique, amortissement à l'attaque du pas (P < 120 kg).",
    tarifTTC: 4043.28,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "monoaxial",
    source: SOURCE_LPPR,
  },
  {
    code: "2745112",
    nomenclature: "Genou monoaxial à frein stabilisateur et rappel mécanique à l'extension, en titane.",
    tarifTTC: 976.08,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "monoaxial",
    source: SOURCE_LPPR,
  },
  {
    code: "2745023",
    nomenclature: "Genou monoaxial, régulation hydraulique, alliage léger, frein d'assistance hydraulique.",
    tarifTTC: 3061.39,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "monoaxial",
    source: SOURCE_LPPR,
  },
  {
    code: "2731794",
    nomenclature: "Genou monoaxial, régulation pneumatique, composite carbone, frein mécanique.",
    tarifTTC: 2630.14,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "monoaxial",
    source: SOURCE_LPPR,
  },
  {
    code: "2721850",
    nomenclature: "Genou monoaxial à mécanique hydraulique de rappel du segment jambier.",
    tarifTTC: 1047.97,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "monoaxial",
    source: SOURCE_LPPR,
  },
  {
    code: "2721198",
    nomenclature: "Genou monoaxial, régulation hydraulique, en titane.",
    tarifTTC: 2097.72,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "monoaxial",
    source: SOURCE_LPPR,
  },
  {
    code: "2797037",
    nomenclature: "Genou monoaxial, régulation hydraulique, alliage léger.",
    tarifTTC: 1739.43,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "monoaxial",
    source: SOURCE_LPPR,
  },
  {
    code: "2777260",
    nomenclature: "Genou monoaxial, régulation hydraulique, alliage léger, réglages dissociés flexion/extension.",
    tarifTTC: 3336.9,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "monoaxial",
    source: SOURCE_LPPR,
  },
  {
    code: "2755270",
    nomenclature: "Genou monoaxial, régulation hydraulique phase pendulaire et phase d'appui, composite carbone renforcé, activité élevée (P < 120 kg).",
    tarifTTC: 4159.62,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "monoaxial",
    source: SOURCE_LPPR,
  },
  {
    code: "2742390",
    nomenclature: "Genou monoaxial, régulation hydraulique phase pendulaire et phase d'appui, composite carbone (P < 120 kg).",
    tarifTTC: 3607.42,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "monoaxial",
    source: SOURCE_LPPR,
  },
  {
    code: "2734670",
    nomenclature: "Genou monoaxial, régulation hydraulique phase pendulaire et phase d'appui, composite et tube carbone, système d'alignement.",
    tarifTTC: 4965.55,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "monoaxial",
    source: SOURCE_LPPR,
  },
  {
    code: "2728674",
    nomenclature: "Genou monoaxial, régulation hydraulique phase pendulaire et phase d'appui, alliage léger renforcé.",
    tarifTTC: 4053.67,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "monoaxial",
    source: SOURCE_LPPR,
  },
  {
    code: "2738508",
    nomenclature: "Genou monoaxial, régulation hydraulique phase pendulaire et phase d'appui, alliage léger.",
    tarifTTC: 4569.88,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "monoaxial",
    source: SOURCE_LPPR,
  },
  {
    code: "2753287",
    nomenclature: "Genou monoaxial à microprocesseur, sécurité hydraulique de la phase d'appui, commande hydraulique de la phase pendulaire. OTTO BOCK, C-LEG 3C100.",
    tarifTTC: 17396.14,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "monoaxial",
    source: SOURCE_LPPR,
  },
  {
    code: "2793482",
    nomenclature: "Genou monoaxial, phase pendulaire pneumatique asservie par microprocesseur, phase d'appui gérée par frein rotatif hydraulique. PROTEOR, HYBRID-1P360.",
    tarifTTC: 15750.29,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "monoaxial",
    source: SOURCE_LPPR,
  },
  {
    code: "2799958",
    nomenclature: "Genou monoaxial à microprocesseur, sécurité de la phase d'appui et régulation de la phase pendulaire par microprocesseur et fluide magnétorhéologique. ÖSSUR, RHEO KNEE (3e génération).",
    tarifTTC: 17044.06,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "microprocesseur",
    source: SOURCE_LPPR,
  },
  {
    code: "2760940",
    nomenclature: "Genou monoaxial à microprocesseur et fluide magnétorhéologique, variante XC. ÖSSUR France, RHEO KNEE XC.",
    tarifTTC: 17044.06,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "microprocesseur",
    source: SOURCE_LPPR,
  },
  {
    code: "2752218",
    nomenclature: "Genou monoaxial hydraulique contrôlé par microprocesseur. OTTO BOCK France, KENEVO.",
    tarifTTC: 16178.41,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "microprocesseur",
    source: SOURCE_LPPR,
  },
  {
    code: "2790696",
    nomenclature: "Genou monoaxial hydropneumatique à microprocesseur, sécurité de la phase d'appui et régulation de la phase pendulaire par vérin hydropneumatique. BLATCHFORD, ORION3.",
    tarifTTC: 16191.86,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "microprocesseur",
    source: SOURCE_LPPR,
  },
  {
    code: "2739229",
    nomenclature: "Genou polycentrique, stabilisation par géométrie du système articulaire, régulation pneumatique assistée par microprocesseur, composite carbone.",
    tarifTTC: 5497.4,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "polycentrique",
    source: SOURCE_LPPR,
  },
  {
    code: "2720230",
    nomenclature: "Genou polycentrique à double articulation à biellettes courtes (à déduire).",
    tarifTTC: 24.11,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "polycentrique",
    source: SOURCE_LPPR,
  },
  {
    code: "2700871",
    nomenclature: "Genou polycentrique à double articulation à biellettes longues.",
    tarifTTC: 407.55,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "polycentrique",
    source: SOURCE_LPPR,
  },
  {
    code: "2733563",
    nomenclature: "Genou polycentrique, stabilisation par géométrie du système articulaire, rappel mécanique à l'extension, composite carbone, verrou facultatif.",
    tarifTTC: 1197.81,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "polycentrique",
    source: SOURCE_LPPR,
  },
  {
    code: "2728645",
    nomenclature: "Genou polycentrique, stabilisation par géométrie du système articulaire, rappel mécanique à l'extension, en titane.",
    tarifTTC: 1090.24,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "polycentrique",
    source: SOURCE_LPPR,
  },
  {
    code: "2703355",
    nomenclature: "Genou polycentrique, stabilisation par géométrie du système articulaire, rappel mécanique à l'extension, composite carbone, amortissement à l'attaque du pas.",
    tarifTTC: 1756.64,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "polycentrique",
    source: SOURCE_LPPR,
  },
  {
    code: "2726215",
    nomenclature: "Genou polycentrique à double articulation à biellettes avec dispositif pneumatique de contrôle de la phase pendulaire.",
    tarifTTC: 1474.79,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "polycentrique",
    source: SOURCE_LPPR,
  },
  {
    code: "2781823",
    nomenclature: "Genou polycentrique, stabilisation par géométrie du système articulaire, régulation pneumatique, composite carbone, régulation pressurisée.",
    tarifTTC: 3340.51,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "polycentrique",
    source: SOURCE_LPPR,
  },
  {
    code: "2733907",
    nomenclature: "Genou polycentrique, stabilisation par géométrie du système articulaire, régulation pneumatique, composite carbone, biellettes longues.",
    tarifTTC: 2163.48,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "polycentrique",
    source: SOURCE_LPPR,
  },
  {
    code: "2714608",
    nomenclature: "Genou polycentrique, stabilisation par géométrie du système articulaire, régulation pneumatique, composite carbone.",
    tarifTTC: 2082.71,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "polycentrique",
    source: SOURCE_LPPR,
  },
  {
    code: "2714318",
    nomenclature: "Genou polycentrique, stabilisation par géométrie du système articulaire, régulation pneumatique, alliage léger, double réglage d'alignement.",
    tarifTTC: 1916.36,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "polycentrique",
    source: SOURCE_LPPR,
  },
  {
    code: "2724736",
    nomenclature: "Genou polycentrique, stabilisation par géométrie du système articulaire, régulation pneumatique, composite carbone, amortissement à l'attaque du pas.",
    tarifTTC: 2658.34,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "polycentrique",
    source: SOURCE_LPPR,
  },
  {
    code: "2747909",
    nomenclature: "Genou polycentrique, stabilisation par géométrie du système articulaire, régulation pneumatique, alliage léger et carbone.",
    tarifTTC: 1859.39,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "polycentrique",
    source: SOURCE_LPPR,
  },
  {
    code: "2758706",
    nomenclature: "Genou polycentrique à barre postérieure (moignon long), rappel hydraulique.",
    tarifTTC: 2872.29,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "polycentrique",
    source: SOURCE_LPPR,
  },
  {
    code: "2710272",
    nomenclature: "Genou polycentrique, stabilisation par géométrie du système articulaire, régulation hydraulique, alliage léger, verrouillage actif, amortissement à l'attaque du pas.",
    tarifTTC: 3118.17,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "polycentrique",
    source: SOURCE_LPPR,
  },
  {
    code: "2755292",
    nomenclature: "Genou polycentrique, stabilisation par géométrie du système articulaire, régulation hydraulique, alliage léger renforcé, verrouillage actif (P < 125 kg).",
    tarifTTC: 5430.8,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "polycentrique",
    source: SOURCE_LPPR,
  },
  {
    code: "2737124",
    nomenclature: "Genou polycentrique, stabilisation par géométrie du système articulaire, régulation hydraulique, alliage léger, amortissement à l'attaque du pas.",
    tarifTTC: 3811.93,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "polycentrique",
    source: SOURCE_LPPR,
  },
  {
    code: "2736662",
    nomenclature: "Genou polycentrique, stabilisation par géométrie du système articulaire, régulation hydraulique, en titane (P < 110 kg).",
    tarifTTC: 2340.43,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "polycentrique",
    source: SOURCE_LPPR,
  },
  {
    code: "2757894",
    nomenclature: "Boîtier de programmation pour genou électronique à microprocesseur (accessoire).",
    tarifTTC: 982.08,
    membre: "inferieur",
    famille: "genoux",
    sousFamille: "polycentrique",
    source: SOURCE_LPPR,
  },
  {
    code: "2736515",
    nomenclature: "Main avec pouce motorisé, système AXON-BUS. OTTO BOCK, MICHELANGELO.",
    tarifTTC: 32275.0,
    membre: "superieur",
    famille: "mains-bras-myoelectriques",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2712526",
    nomenclature: "Pronosupination motorisée AXON-ROTATION pour main MICHELANGELO.",
    tarifTTC: 5427.0,
    membre: "superieur",
    famille: "mains-bras-myoelectriques",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2732345",
    nomenclature: "Gant de recouvrement AXON SKIN pour main MICHELANGELO (limité à 2 par an).",
    tarifTTC: 450.0,
    membre: "superieur",
    famille: "mains-bras-myoelectriques",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2779358",
    nomenclature: "Main avec pouce motorisé, variante transcarpienne. OTTO BOCK, MICHELANGELO TRANSCARPIENNE.",
    tarifTTC: 32275.0,
    membre: "superieur",
    famille: "mains-bras-myoelectriques",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2714710",
    nomenclature: "Main myoélectrique multi-préhension (18 modes), pack complet avec gants de recouvrement, kit électrodes et batteries. TOUCH BIONICS/ÖSSUR, I-LIMB ULTRA.",
    tarifTTC: 27270.37,
    membre: "superieur",
    famille: "mains-bras-myoelectriques",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2706833",
    nomenclature: "Prothèse de main partielle motorisée, pouce + 1 doigt. ÖSSUR, I-DIGITS.",
    tarifTTC: 24600.0,
    membre: "superieur",
    famille: "mains-bras-myoelectriques",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2747810",
    nomenclature: "Recouvrement silicone pour doigt I-DIGITS, par taille et couleur.",
    tarifTTC: 21.0,
    membre: "superieur",
    famille: "mains-bras-myoelectriques",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2762100",
    nomenclature: "Coude myoélectrique motorisé, commande par 3 éléments maximum. OTTO BOCK, DYNAMICARM 12K100N.",
    tarifTTC: 30889.0,
    membre: "superieur",
    famille: "mains-bras-myoelectriques",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2797712",
    nomenclature: "Coude myoélectrique motorisé, commande par 8 éléments maximum. OTTO BOCK, DYNAMICARM 12K110N.",
    tarifTTC: 30889.0,
    membre: "superieur",
    famille: "mains-bras-myoelectriques",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2727551",
    nomenclature: "Pied à restitution d'énergie, classe I. ORTHO, AERIS K2.",
    tarifTTC: 613.59,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-1",
    source: SOURCE_LPPR,
  },
  {
    code: "2787464",
    nomenclature: "Pied à restitution d'énergie, classe I. OTTO BOCK, DYNAMIC MOTION 1D35.",
    tarifTTC: 613.59,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-1",
    source: SOURCE_LPPR,
  },
  {
    code: "2733439",
    nomenclature: "Pied à restitution d'énergie, classe I. OTTO BOCK, 1D10.",
    tarifTTC: 613.59,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-1",
    source: SOURCE_LPPR,
  },
  {
    code: "2735467",
    nomenclature: "Pied à restitution d'énergie, classe I. OTTO BOCK, AQUA FOOT.",
    tarifTTC: 613.59,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-1",
    source: SOURCE_LPPR,
  },
  {
    code: "2716530",
    nomenclature: "Pied à restitution d'énergie, classe I. OTTO BOCK, ADJUST 1M10.",
    tarifTTC: 613.59,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-1",
    source: SOURCE_LPPR,
  },
  {
    code: "2709493",
    nomenclature: "Pied à restitution d'énergie, classe I. PROTEOR, DYNASTEP.",
    tarifTTC: 613.59,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-1",
    source: SOURCE_LPPR,
  },
  {
    code: "2793074",
    nomenclature: "Pied à restitution d'énergie, classe I. PROTEOR, UPYA.",
    tarifTTC: 613.59,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-1",
    source: SOURCE_LPPR,
  },
  {
    code: "2707471",
    nomenclature: "Pied à restitution d'énergie, classe I. TRINYTEC, 1H11Y.",
    tarifTTC: 613.59,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-1",
    source: SOURCE_LPPR,
  },
  {
    code: "2760838",
    nomenclature: "Pied à restitution d'énergie, classe I. G2M, ENERGY FOOT.",
    tarifTTC: 613.59,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-1",
    source: SOURCE_LPPR,
  },
  {
    code: "2790093",
    nomenclature: "Pied à restitution d'énergie, classe I. ÖSSUR, BALANCE FOOT S.",
    tarifTTC: 613.59,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-1",
    source: SOURCE_LPPR,
  },
  {
    code: "2738709",
    nomenclature: "Pied à restitution d'énergie, classe II. GO ORTHO, WINGED FOOT.",
    tarifTTC: 972.43,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-2",
    source: SOURCE_LPPR,
  },
  {
    code: "2794079",
    nomenclature: "Pied à restitution d'énergie, classe II. ÖSSUR, FLEX-FOOT BALANCE.",
    tarifTTC: 972.43,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-2",
    source: SOURCE_LPPR,
  },
  {
    code: "2756825",
    nomenclature: "Pied à restitution d'énergie, classe II. ÖSSUR, BALANCE FOOT J.",
    tarifTTC: 972.43,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-2",
    source: SOURCE_LPPR,
  },
  {
    code: "2769294",
    nomenclature: "Pied à restitution d'énergie, classe II. ÖSSUR, FLEX-FOOT ASSURE.",
    tarifTTC: 972.43,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-2",
    source: SOURCE_LPPR,
  },
  {
    code: "2794487",
    nomenclature: "Pied à restitution d'énergie, classe II. OTTO BOCK, TRIAS 1C30.",
    tarifTTC: 972.43,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-2",
    source: SOURCE_LPPR,
  },
  {
    code: "2709234",
    nomenclature: "Pied à restitution d'énergie, classe II. OTTO BOCK, TERION K2.",
    tarifTTC: 972.43,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-2",
    source: SOURCE_LPPR,
  },
  {
    code: "2713980",
    nomenclature: "Pied à restitution d'énergie, classe II. OTTO BOCK, PROMENADE.",
    tarifTTC: 972.43,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-2",
    source: SOURCE_LPPR,
  },
  {
    code: "2709122",
    nomenclature: "Pied à restitution d'énergie, classe II. ORTHO, DURAWALK.",
    tarifTTC: 972.43,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-2",
    source: SOURCE_LPPR,
  },
  {
    code: "2774250",
    nomenclature: "Pied à restitution d'énergie, classe II. PROTEOR, DYNASTAR (gamme 1A500).",
    tarifTTC: 972.43,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-2",
    source: SOURCE_LPPR,
  },
  {
    code: "2759640",
    nomenclature: "Pied à restitution d'énergie, classe II. PROTEOR, DYNACITY 1A510.",
    tarifTTC: 972.43,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-2",
    source: SOURCE_LPPR,
  },
  {
    code: "2797362",
    nomenclature: "Pied à restitution d'énergie, classe II. PROTEOR, RUSH ROVER.",
    tarifTTC: 972.43,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-2",
    source: SOURCE_LPPR,
  },
  {
    code: "2724009",
    nomenclature: "Pied à restitution d'énergie, classe II. PROTEOR, EXALTO.",
    tarifTTC: 972.43,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-2",
    source: SOURCE_LPPR,
  },
  {
    code: "2729461",
    nomenclature: "Pied à restitution d'énergie, classe II. PROTEOR, MAHI.",
    tarifTTC: 972.43,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-2",
    source: SOURCE_LPPR,
  },
  {
    code: "2780344",
    nomenclature: "Pied à restitution d'énergie, classe II. TRINYTEC, DYNAMIC CARBON FOOT 1H04Y.",
    tarifTTC: 972.43,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-2",
    source: SOURCE_LPPR,
  },
  {
    code: "2744970",
    nomenclature: "Pied à restitution d'énergie, classe III. ALPS, BIOSTEP LP.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2761230",
    nomenclature: "Pied à restitution d'énergie, classe III. ALPS, BIOSTEP EVO.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2772209",
    nomenclature: "Pied à restitution d'énergie, classe III. BLATCHFORD, ELITE.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2759338",
    nomenclature: "Pied à restitution d'énergie, classe III. BLATCHFORD, ESPRIT.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2784974",
    nomenclature: "Pied à restitution d'énergie, classe III. FILLAUER, AERIS PERFORMANCE 2.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2728579",
    nomenclature: "Pied à restitution d'énergie, classe III. FILLAUER, AERIS PERFORMANCE LP.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2740830",
    nomenclature: "Pied à restitution d'énergie, classe III. LINDHE, XTEND FOOT H100.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2765592",
    nomenclature: "Pied à restitution d'énergie, classe III. LINDHE, XTEND FOOT H100 (version 2021).",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2724564",
    nomenclature: "Pied à restitution d'énergie, classe III. OKO SOLUTION, AERIS SOLUTION.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2713750",
    nomenclature: "Pied à restitution d'énergie, classe III. OKO SOLUTION, SYNERGY X3.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2754186",
    nomenclature: "Pied à restitution d'énergie, classe III. ORTHO, DURALITE.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2747230",
    nomenclature: "Pied à restitution d'énergie, classe III. ORTHO, META ARC.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2762197",
    nomenclature: "Pied à restitution d'énergie, classe III. ÖSSUR, SOLEUS.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2704461",
    nomenclature: "Pied à restitution d'énergie, classe III. ÖSSUR, VELOCITY.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2706566",
    nomenclature: "Pied à restitution d'énergie, classe III. ÖSSUR, CELSUS.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2734700",
    nomenclature: "Pied à restitution d'énergie, classe III. ÖSSUR, VARI-FLEX.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2712325",
    nomenclature: "Pied à restitution d'énergie, classe III. ÖSSUR, RE-FLEX.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2729521",
    nomenclature: "Pied à restitution d'énergie, classe III. ÖSSUR, PRO-FLEX XC.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2732724",
    nomenclature: "Pied à restitution d'énergie, classe III. ÖSSUR, PRO-FLEX LP.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2747944",
    nomenclature: "Pied à restitution d'énergie, classe III. ÖSSUR, PRO-FLEX ST.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2788498",
    nomenclature: "Pied à restitution d'énergie, classe III. ÖSSUR, PRO-FLEX MODULAR.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2770311",
    nomenclature: "Pied à restitution d'énergie, classe III. ÖSSUR, CHEETAH XPLORE.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2752187",
    nomenclature: "Pied à restitution d'énergie, classe III. OTTO BOCK, TRITON.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2730694",
    nomenclature: "Pied à restitution d'énergie, classe III. OTTO BOCK, CHALLENGER 1E95.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2764470",
    nomenclature: "Pied à restitution d'énergie, classe III. OTTO BOCK, TALEO.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2738098",
    nomenclature: "Pied à restitution d'énergie, classe III. OTTO BOCK, TALEO LP.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2705147",
    nomenclature: "Pied à restitution d'énergie, classe III. OTTO BOCK, EVANTO.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2755458",
    nomenclature: "Pied à restitution d'énergie, classe III. PROTEOR, DYNA C.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2784336",
    nomenclature: "Pied à restitution d'énergie, classe III. PROTEOR, DYNA J.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2739399",
    nomenclature: "Pied à restitution d'énergie, classe III. PROTEOR, DYNATREK 1A600.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2735119",
    nomenclature: "Pied à restitution d'énergie, classe III. PROTEOR, RUSH HIPRO.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2781705",
    nomenclature: "Pied à restitution d'énergie, classe III. PROTEOR, RUSH RAMPAGE LP.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2782219",
    nomenclature: "Pied à restitution d'énergie, classe III. PROTEOR, SIERRA.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2737450",
    nomenclature: "Pied à restitution d'énergie, classe III. PROTEOR, DYNADAPT.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2700010",
    nomenclature: "Pied à restitution d'énergie, classe III. PROTEOR, HIGHLANDER.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2791454",
    nomenclature: "Pied à restitution d'énergie, classe III. PROTEOR, FREEDOM SHOCKWAVE.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2764291",
    nomenclature: "Pied à restitution d'énergie, classe III. PROTEOR, FREEDOM AGILIX.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2743604",
    nomenclature: "Pied à restitution d'énergie, classe III. PROTEOR, RUSH RAMPAGE.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "classe-3",
    source: SOURCE_LPPR,
  },
  {
    code: "2791738",
    nomenclature: "Pied à restitution d'énergie, amputation basse de jambe. OTTO BOCK, CHOPART.",
    tarifTTC: 1857.61,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "amputation-basse-jambe",
    source: SOURCE_LPPR,
  },
  {
    code: "2731676",
    nomenclature: "Pied à restitution d'énergie, amputation basse de jambe. OTTO BOCK, LOW PROFIL AXTION 1E56.",
    tarifTTC: 1857.61,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "amputation-basse-jambe",
    source: SOURCE_LPPR,
  },
  {
    code: "2711975",
    nomenclature: "Pied à restitution d'énergie, amputation basse de jambe. OTTO BOCK, LO RIDER.",
    tarifTTC: 1857.61,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "amputation-basse-jambe",
    source: SOURCE_LPPR,
  },
  {
    code: "2768679",
    nomenclature: "Pied à restitution d'énergie, amputation basse de jambe. PROTEOR, RUSH CHOPART.",
    tarifTTC: 1857.61,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "amputation-basse-jambe",
    source: SOURCE_LPPR,
  },
  {
    code: "2745900",
    nomenclature: "Pied à restitution d'énergie, amputation basse de jambe. PROTEOR, PACIFICA LP.",
    tarifTTC: 1857.61,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "amputation-basse-jambe",
    source: SOURCE_LPPR,
  },
  {
    code: "2705360",
    nomenclature: "Pied à restitution d'énergie, enfant. PROTEOR, RUSH KID.",
    tarifTTC: 2512.82,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "enfant",
    source: SOURCE_LPPR,
  },
  {
    code: "2721749",
    nomenclature: "Pied à restitution d'énergie, remplacement du revêtement esthétique.",
    tarifTTC: 211.35,
    membre: "inferieur",
    famille: "pieds",
    sousFamille: "accessoire",
    source: SOURCE_LPPR,
  },
  {
    code: "2783242",
    nomenclature: "Emboîture fémorale sub-ischiatique à double fût. PROTEOR, I-SUB.",
    tarifTTC: 1171.05,
    membre: "inferieur",
    famille: "emboitures",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2774349",
    nomenclature: "Ensemble genou-cheville-pied à microprocesseur. PROTEOR, SYNSYS.",
    tarifTTC: 31544.5,
    membre: "inferieur",
    famille: "chevilles-hanches",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2763943",
    nomenclature: "Articulation de hanche polycentrique hydraulique. OTTO BOCK, HELIX 3D 7E10.",
    tarifTTC: 9442.25,
    membre: "inferieur",
    famille: "chevilles-hanches",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2788707",
    nomenclature: "Prothèse en résines stratifiées, sans manchon intermédiaire, point d'appui sous-ischiatique, fermeture antérieure. Pied du patient positionné au-dessus du genou sain.",
    tarifTTC: 1972.37,
    membre: "inferieur",
    famille: "malformations-congenitales",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2714650",
    nomenclature: "Prothèse en résines stratifiées, sans manchon intermédiaire, point d'appui sous-ischiatique. Pied du patient positionné au niveau du genou sain.",
    tarifTTC: 2011.89,
    membre: "inferieur",
    famille: "malformations-congenitales",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2786944",
    nomenclature: "Prothèse en résines stratifiées, emboîture en cuir moulé, fermeture antérieure, armée par deux montants latéraux. Pied du patient positionné au niveau du genou sain.",
    tarifTTC: 2143.93,
    membre: "inferieur",
    famille: "malformations-congenitales",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2704107",
    nomenclature: "Prothèse en résines stratifiées, sans manchon intermédiaire, appui sous-ischiatique enveloppant le genou. Segment cuisse-genou normal, raccourcissement en dessous du genou.",
    tarifTTC: 1653.78,
    membre: "inferieur",
    famille: "malformations-congenitales",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2712176",
    nomenclature: "Prothèse en résines stratifiées, sans manchon intermédiaire, appui sur le tendon rotulien. Segment cuisse-genou normal, raccourcissement en dessous du genou.",
    tarifTTC: 1512.01,
    membre: "inferieur",
    famille: "malformations-congenitales",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2723100",
    nomenclature: "Prothèse en cuir et acier, gaine en cuir moulé garnie intérieurement, deux montants latéraux réunis par deux embrasses. Segment cuisse-genou normal, raccourcissement en dessous du genou.",
    tarifTTC: 1694.43,
    membre: "inferieur",
    famille: "malformations-congenitales",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2766516",
    nomenclature: "Cuissard en cuir sans articulation de genou, montants solidarisés à l'emboîture.",
    tarifTTC: 491.93,
    membre: "inferieur",
    famille: "malformations-congenitales",
    sousFamille: "adjonction",
    source: SOURCE_LPPR,
  },
  {
    code: "2780887",
    nomenclature: "Cuissard en cuir avec articulation de genou à chape à roulements à billes.",
    tarifTTC: 582.81,
    membre: "inferieur",
    famille: "malformations-congenitales",
    sousFamille: "adjonction",
    source: SOURCE_LPPR,
  },
  {
    code: "2703065",
    nomenclature: "Manchon intermédiaire amovible en caoutchouc mousse, garni en peau de cheval.",
    tarifTTC: 173.23,
    membre: "inferieur",
    famille: "malformations-congenitales",
    sousFamille: "adjonction",
    source: SOURCE_LPPR,
  },
  {
    code: "2792703",
    nomenclature: "Supplément pour confection d'une orthoprothèse en composite de carbone (prothèses PI23, PI24, PI26).",
    tarifTTC: 451.8,
    membre: "inferieur",
    famille: "malformations-congenitales",
    sousFamille: "adjonction",
    source: SOURCE_LPPR,
  },
  {
    code: "2702947",
    nomenclature: "Supplément pour confection d'une orthoprothèse en composite de carbone (prothèses PI46).",
    tarifTTC: 366.56,
    membre: "inferieur",
    famille: "malformations-congenitales",
    sousFamille: "adjonction",
    source: SOURCE_LPPR,
  },
  {
    code: "2760643",
    nomenclature: "Manchon préfabriqué en silicone ou copolymère de qualité médicale, suspension de la prothèse.",
    tarifTTC: 1059.25,
    membre: "inferieur",
    famille: "manchons",
    sousFamille: "femoral",
    source: SOURCE_LPPR,
  },
  {
    code: "2798404",
    nomenclature: "Manchon fémoral polyuréthane préfabriqué.",
    tarifTTC: 1606.48,
    membre: "inferieur",
    famille: "manchons",
    sousFamille: "femoral",
    source: SOURCE_LPPR,
  },
  {
    code: "2738030",
    nomenclature: "Manchon injecté et tramé en silicone ou copolymère de qualité médicale, réalisé sur moulage.",
    tarifTTC: 1157.61,
    membre: "inferieur",
    famille: "manchons",
    sousFamille: "femoral",
    source: SOURCE_LPPR,
  },
  {
    code: "2755122",
    nomenclature: "Manchon fémoral polyuréthane injecté et tramé.",
    tarifTTC: 1704.84,
    membre: "inferieur",
    famille: "manchons",
    sousFamille: "femoral",
    source: SOURCE_LPPR,
  },
  {
    code: "2794346",
    nomenclature: "Cupule distale en silicone ou copolymère de qualité médicale, en adjonction au manchon.",
    tarifTTC: 210.12,
    membre: "inferieur",
    famille: "manchons",
    sousFamille: "femoral",
    source: SOURCE_LPPR,
  },
  {
    code: "2750751",
    nomenclature: "Manchon tibial court en caoutchouc, ne dépassant pas les condyles fémoraux.",
    tarifTTC: 156.88,
    membre: "inferieur",
    famille: "manchons",
    sousFamille: "tibial",
    source: SOURCE_LPPR,
  },
  {
    code: "2712532",
    nomenclature: "Manchon tibial court en mousse de polyéthylène, ne dépassant pas les condyles fémoraux.",
    tarifTTC: 107.88,
    membre: "inferieur",
    famille: "manchons",
    sousFamille: "tibial",
    source: SOURCE_LPPR,
  },
  {
    code: "2796090",
    nomenclature: "Manchon tibial haut à accrochage distal en caoutchouc, dépassant les condyles fémoraux.",
    tarifTTC: 583.06,
    membre: "inferieur",
    famille: "manchons",
    sousFamille: "tibial",
    source: SOURCE_LPPR,
  },
  {
    code: "2706997",
    nomenclature: "Manchon tibial haut à accrochage distal en silicone de qualité médicale.",
    tarifTTC: 1196.71,
    membre: "inferieur",
    famille: "manchons",
    sousFamille: "tibial",
    source: SOURCE_LPPR,
  },
  {
    code: "2787949",
    nomenclature: "Manchon tibial en gel de polyuréthane de qualité médicale, personnalisé, réalisé sur moulage.",
    tarifTTC: 1598.27,
    membre: "inferieur",
    famille: "manchons",
    sousFamille: "tibial",
    source: SOURCE_LPPR,
  },
  {
    code: "2722559",
    nomenclature: "Manchon tibial préfabriqué et standardisé, en silicone de qualité médicale, accrochage distal ou valve.",
    tarifTTC: 1042.94,
    membre: "inferieur",
    famille: "manchons",
    sousFamille: "tibial",
    source: SOURCE_LPPR,
  },
  {
    code: "2789204",
    nomenclature: "Manchon tibial en gel copolymère préfabriqué, accrochage distal ou valve de dépressurisation.",
    tarifTTC: 1291.17,
    membre: "inferieur",
    famille: "manchons",
    sousFamille: "tibial",
    source: SOURCE_LPPR,
  },
  {
    code: "2761520",
    nomenclature: "Manchon tibial préfabriqué 2e génération, gel épais de silicone (épaisseur > 4 mm).",
    tarifTTC: 1347.77,
    membre: "inferieur",
    famille: "manchons",
    sousFamille: "tibial",
    source: SOURCE_LPPR,
  },
  {
    code: "2746123",
    nomenclature: "Manchon tibial en gel de polyuréthane de qualité médicale, accrochage distal ou valve.",
    tarifTTC: 1490.72,
    membre: "inferieur",
    famille: "manchons",
    sousFamille: "tibial",
    source: SOURCE_LPPR,
  },
  {
    code: "2740942",
    nomenclature: "Cupule distale en silicone ou copolymère de qualité médicale, en adjonction au manchon tibial.",
    tarifTTC: 210.12,
    membre: "inferieur",
    famille: "manchons",
    sousFamille: "tibial",
    source: SOURCE_LPPR,
  },
  {
    code: "2720307",
    nomenclature: "Manchon intermédiaire pour emboîture de cuisse.",
    tarifTTC: 147.99,
    membre: "inferieur",
    famille: "manchons",
    sousFamille: "generique",
    source: SOURCE_LPPR,
  },
  {
    code: "2734746",
    nomenclature: "Manchon intermédiaire, adaptable aux prothèses pour amputation d'avant-bras.",
    tarifTTC: 127.13,
    membre: "superieur",
    famille: "manchons",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2748470",
    nomenclature: "Manchon intermédiaire, adaptable aux prothèses pour amputation de bras.",
    tarifTTC: 127.13,
    membre: "superieur",
    famille: "manchons",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2782515",
    nomenclature: "Manchon d'avant-bras en silicone sans accrochage distal.",
    tarifTTC: 267.77,
    membre: "superieur",
    famille: "manchons",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2782550",
    nomenclature: "Manchon de bras en silicone préfabriqué ou injecté de qualité médicale.",
    tarifTTC: 957.08,
    membre: "superieur",
    famille: "manchons",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2765362",
    nomenclature: "Manchon d'avant-bras en silicone préfabriqué ou injecté de qualité médicale.",
    tarifTTC: 957.08,
    membre: "superieur",
    famille: "manchons",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2787286",
    nomenclature: "Gaine de suspension externe de bras en silicone ou gel de silicone.",
    tarifTTC: 69.72,
    membre: "superieur",
    famille: "manchons",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2702410",
    nomenclature: "Gaine de suspension externe d'avant-bras en silicone ou gel de silicone.",
    tarifTTC: 69.72,
    membre: "superieur",
    famille: "manchons",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2715128",
    nomenclature: "Valve d'obturation, adaptable aux prothèses pour amputation d'avant-bras.",
    tarifTTC: 37.32,
    membre: "superieur",
    famille: "adjonctions",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2779341",
    nomenclature: "Valve d'obturation, adaptable aux prothèses pour amputation de bras.",
    tarifTTC: 37.32,
    membre: "superieur",
    famille: "adjonctions",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2796032",
    nomenclature: "Corselet de fixation avec articulation d'épaule double, en cuir moulé.",
    tarifTTC: 374.68,
    membre: "superieur",
    famille: "adjonctions",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2751992",
    nomenclature: "Corselet de fixation avec articulation d'épaule double, stratifié.",
    tarifTTC: 321.36,
    membre: "superieur",
    famille: "adjonctions",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2703964",
    nomenclature: "Gainage d'un montant ou d'une embrasse (tête d'articulation comprise).",
    tarifTTC: 10.78,
    membre: "inferieur",
    famille: "adjonctions",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2700032",
    nomenclature: "Verrou de coude.",
    tarifTTC: 105.16,
    membre: "superieur",
    famille: "adjonctions",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2770179",
    nomenclature: "Main souple avec gant à manchette longue, montage sur tube d'avant-bras.",
    tarifTTC: 417.86,
    membre: "superieur",
    famille: "adjonctions",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2792910",
    nomenclature: "Cercle acier pour consolider une emboîture (membre inférieur).",
    tarifTTC: 38.46,
    membre: "inferieur",
    famille: "adjonctions",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2741344",
    nomenclature: "Protège-pantalon (membre inférieur).",
    tarifTTC: 60.36,
    membre: "inferieur",
    famille: "adjonctions",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2799326",
    nomenclature: "Faux moignon (membre inférieur).",
    tarifTTC: 253.18,
    membre: "inferieur",
    famille: "adjonctions",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2759491",
    nomenclature: "Valve de dépressurisation, emboîture avec manchon (membre inférieur).",
    tarifTTC: 212.73,
    membre: "inferieur",
    famille: "adjonctions",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2773427",
    nomenclature: "Bonnet couvre-moignon pour cuisse.",
    tarifTTC: 18.1,
    membre: "inferieur",
    famille: "accessoires",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2706738",
    nomenclature: "Bonnet couvre-moignon pour jambe.",
    tarifTTC: 20.81,
    membre: "inferieur",
    famille: "accessoires",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2708677",
    nomenclature: "Gaine couvre-moignon en textile artificiel 100 % polyamide (membre inférieur).",
    tarifTTC: 9.45,
    membre: "inferieur",
    famille: "accessoires",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2729389",
    nomenclature: "Dispositif de maintien des prothèses tibiales contact, tricot tramé élastique.",
    tarifTTC: 49.97,
    membre: "inferieur",
    famille: "accessoires",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2740362",
    nomenclature: "Chausse-prothèse (membre inférieur).",
    tarifTTC: 62.11,
    membre: "inferieur",
    famille: "accessoires",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2744851",
    nomenclature: "Bonnet couvre-moignon pour bras, prothèse classique (épaisseur 5 fils).",
    tarifTTC: 12.48,
    membre: "superieur",
    famille: "accessoires",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2758592",
    nomenclature: "Bonnet couvre-moignon pour avant-bras, prothèse classique (épaisseur 5 fils).",
    tarifTTC: 11.69,
    membre: "superieur",
    famille: "accessoires",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2778270",
    nomenclature: "Bonnet couvre-moignon pour bras, prothèse contact (épaisseur 3 fils).",
    tarifTTC: 11.99,
    membre: "superieur",
    famille: "accessoires",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2700782",
    nomenclature: "Bonnet couvre-moignon pour avant-bras, prothèse contact (épaisseur 3 fils).",
    tarifTTC: 11.44,
    membre: "superieur",
    famille: "accessoires",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
  {
    code: "2705176",
    nomenclature: "Gaine couvre-moignon en textile artificiel 100 % polyamide (membre supérieur).",
    tarifTTC: 9.45,
    membre: "superieur",
    famille: "accessoires",
    sousFamille: undefined,
    source: SOURCE_LPPR,
  },
];
