export type Orthoprothesiste = {
  nom: string
  adresse: string
  cp: string
  ville: string
  departement: string
  telephone: string
  email?: string
  siteWeb?: string
}

export const orthoprothesistes: Orthoprothesiste[] = [
  {
    nom: "ATLANTIQUE ORTHO",
    adresse: "317 route de Toulouse",
    cp: "33140",
    ville: "Villenave D’Ornon",
    departement: "33",
    telephone: "05 56 49 09 09",
    siteWeb: "https://atlantiqueortho.com",
  },
  {
    nom: "PROTEOR MÉRIGNAC",
    adresse: "498 avenue de Verdun",
    cp: "33700",
    ville: "Merignac",
    departement: "33",
    telephone: "05 56 12 06 86",
    email: "merignac.sante@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "ALBATROS BÈGLES",
    adresse: "14 avenue Jeanne d'Arc",
    cp: "33130",
    ville: "Bègles",
    departement: "33",
    telephone: "05 56 85 05 09",
    email: "albatros@albatros-france.fr",
    siteWeb: "https://albatros-france.fr",
  },
  {
    nom: "PROTEOR BORDEAUX",
    adresse: "5 allée Newton ZI Bersol",
    cp: "33600",
    ville: "Bordeaux Pessac",
    departement: "33",
    telephone: "05 57 26 10 40",
    email: "bordeaux@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "DOMITAL ORTHOPEDIE",
    adresse: "ZA JEAN ZAY 3 rue Condorcet",
    cp: "33150",
    ville: "Cenon",
    departement: "33",
    telephone: "05 56 40 42 53",
    siteWeb: "https://www.domital-orthopedie.com",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (BORDEAUX)",
    adresse: "144 Avenue du Médoc Centre commercial Le Vigean",
    cp: "33320",
    ville: "Eysines",
    departement: "33",
    telephone: "05 56 05 42 26",
    email: "bordeaux@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/agence-bordeaux/",
  },
  {
    nom: "LAGARRIGUE PESSAC",
    adresse: "Parc Biogalien 27 allée Charles Darwin",
    cp: "33600",
    ville: "Pessac",
    departement: "33",
    telephone: "05 56 47 60 07",
    email: "pessac@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "LAGARRIGUE LIBOURNE",
    adresse: "147 rue de la Marne",
    cp: "33500",
    ville: "Libourne",
    departement: "33",
    telephone: "05 33 03 00 34",
    email: "libourne@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "LAGARRIGUE COGNAC",
    adresse: "35 rue de Bellefonds",
    cp: "16100",
    ville: "Cognac",
    departement: "16",
    telephone: "05 45 82 23 07",
    email: "cognac@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "ALBATROS FRANCE",
    adresse: "Z.I. de Maury R.N. 113 40 route de Marceau",
    cp: "47130",
    ville: "Port Sainte Marie",
    departement: "47",
    telephone: "05 53 95 23 48",
    email: "albatros@albatros-france.fr",
    siteWeb: "http://www.albatros-france.fr",
  },
  {
    nom: "PROTEOR ANGOULÊME",
    adresse: "30 rue Victor Hugo",
    cp: "16400",
    ville: "La Couronne",
    departement: "16",
    telephone: "05 49 61 91 01",
    email: "angouleme@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "PROTEOR MONT-DE-MARSAN",
    adresse: "3 allée de l'Oranger",
    cp: "40000",
    ville: "Mont-De-Marsan",
    departement: "40",
    telephone: "05 58 51 14 68",
    email: "proteor.montdemarsan@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "LAGARRIGUE ANGOULÊME",
    adresse: "187 rue de la Tourganier",
    cp: "16000",
    ville: "Angouleme",
    departement: "16",
    telephone: "05 45 38 49 62",
    email: "angouleme@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "ALBATROS PÉRIGUEUX",
    adresse: "157 avenue du Maréchal Juin",
    cp: "24000",
    ville: "Perigueux",
    departement: "24",
    telephone: "05 53 06 96 49",
    email: "albatros@albatros-france.fr",
    siteWeb: "https://albatros-france.fr",
  },
  {
    nom: "PROTEOR PERIGUEUX",
    adresse: "202/204 avenue Michel Grandou",
    cp: "24750",
    ville: "Trelissac",
    departement: "24",
    telephone: "05 53 54 36 50",
    email: "perigueux@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "PROTEOR AGEN",
    adresse: "39 rue Robespierre",
    cp: "47000",
    ville: "Agen",
    departement: "47",
    telephone: "05 53 68 05 64",
    email: "agen@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "LAGARRIGUE AGEN",
    adresse: "852, avenue du Maréchal Leclerc",
    cp: "47000",
    ville: "Agen",
    departement: "47",
    telephone: "05 53 98 33 65",
    email: "agen@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "LAGARRIGUE LA ROCHELLE",
    adresse: "55 rue Victor Hugo",
    cp: "17000",
    ville: "La Rochelle",
    departement: "17",
    telephone: "05 46 34 79 85",
    email: "larochelle@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "EQUIP'SANTE",
    adresse: "14 rue des Greffières",
    cp: "17140",
    ville: "Lagord",
    departement: "17",
    telephone: "05 46 34 39 06",
    email: "NC",
    siteWeb: "http://www.equip-sante.com/",
  },
  {
    nom: "PROTEOR NIORT",
    adresse: "493 avenue de Paris",
    cp: "79000",
    ville: "Niort",
    departement: "79",
    telephone: "05 49 35 30 30",
    email: "niort@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (ANGLET)",
    adresse: "3 rue de lestandau",
    cp: "64600",
    ville: "Anglet",
    departement: "64",
    telephone: "05 59 31 42 84",
    email: "anglet@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/agence-anglet/",
  },
  {
    nom: "PROTEOR BAYONNE",
    adresse: "4 allée Didier Daurat",
    cp: "64100",
    ville: "Bayonne",
    departement: "64",
    telephone: "05 59 70 56 61",
    email: "bayonne@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "PROTEOR BRIVE",
    adresse: "34 avenue Ribot",
    cp: "19100",
    ville: "Brive La Gaillarde",
    departement: "19",
    telephone: "05 55 17 24 18",
    email: "brive@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "LAGARRIGUE PAU",
    adresse: "14 rue Johannes Kepler",
    cp: "64000",
    ville: "Pau",
    departement: "64",
    telephone: "NC",
    email: "pau@groupelagarrigue.com",
    siteWeb: "https://lagarrigue.com/",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (PAU)",
    adresse: "14 rue Jean Zay",
    cp: "64000",
    ville: "Pau",
    departement: "64",
    telephone: "05 59 30 52 43",
    email: "pau@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/pau-orthodynamic/",
  },
  {
    nom: "LAGARRIGUE",
    adresse: "ZAC Golf - 15 Impasse Oihana",
    cp: "64200",
    ville: "Bassussarry",
    departement: "64",
    telephone: "NC",
    email: "bayonne@groupelagarrigue.com",
    siteWeb: "https://lagarrigue.com/",
  },
  {
    nom: "LAGARRIGUE BRIVE-LA-GAILLARDE",
    adresse: "23 avenue Maréchal Bugeaud",
    cp: "19100",
    ville: "Brive La Gaillarde",
    departement: "19",
    telephone: "05 55 74 31 30",
    email: "brive@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "LAGARRIGUE LIMOGES",
    adresse: "43 rue de la Conque",
    cp: "87000",
    ville: "Limoges",
    departement: "87",
    telephone: "05 55 01 25 25",
    email: "limoges@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "PROTEOR MONTAUBAN",
    adresse: "110 rue François Mauriac",
    cp: "82000",
    ville: "Montauban",
    departement: "82",
    telephone: "05 63 65 53 45",
    email: "proteor.montauban@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "PROTEOR LIMOGES",
    adresse: "5 rue Santos Dumont",
    cp: "87000",
    ville: "Limoges",
    departement: "87",
    telephone: "05 87 41 83 03",
    email: "proteor.limoges@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "EQUIP'SANTE",
    adresse: "23, bd de l'Aumônerie",
    cp: "85400",
    ville: "Lucon",
    departement: "85",
    telephone: "02 51 27 92 63",
    email: "NC",
    siteWeb: "http://www.equip-sante.com/",
  },
  {
    nom: "ALBATROS TOULOUSE",
    adresse: "Parc Pythagore 109 impasse Thalès - Bat. 17",
    cp: "31620",
    ville: "",
    departement: "31",
    telephone: "05 34 52 64 26",
    email: "albatros@albatros-france.fr",
    siteWeb: "https://albatros-france.fr",
  },
  {
    nom: "OCTO31",
    adresse: "4 chemin de la Ménude",
    cp: "31770",
    ville: "Colomiers",
    departement: "31",
    telephone: "05 61 84 33 46",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "PROTEOR POITIERS",
    adresse: "116 rue des Artisans ZA de Beaubâton",
    cp: "86550",
    ville: "Mignaloux-Bauvoir",
    departement: "86",
    telephone: "05 49 38 87 17",
    email: "poitiers@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "CAP ORTHOPEDIE",
    adresse: "4 rue Albert Einstein Parc Numérimer",
    cp: "85340",
    ville: "Les Sables D'Olonne",
    departement: "85",
    telephone: "02 51 32 57 38",
    email: "accueil@cap-orthopedie.com",
    siteWeb: "https://www.cap-orthopedie.com",
  },
  {
    nom: "ORTHO EVOLUTION",
    adresse: "7 rue Isabelle Eberhardt",
    cp: "31200",
    ville: "Toulouse",
    departement: "31",
    telephone: "05 32 09 71 23",
    email: "orthoevolution31@gmail.com",
    siteWeb: "https://ortho-evolution.fr/",
  },
  {
    nom: "APPAREILLAGES SUD PROTHESE",
    adresse: "7 rue Isabelle Eberhardt",
    cp: "31000",
    ville: "Toulouse",
    departement: "31",
    telephone: "05 61 13 06 67",
  },
  {
    nom: "LAGARRIGUE TOULOUSE",
    adresse: "50-56-58 Chemin Baluffet ZI Baluffet",
    cp: "31300",
    ville: "Toulouse",
    departement: "31",
    telephone: "05 61 49 30 31",
    email: "toulouse@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "PROTEOR TOULOUSE",
    adresse: "5 Rue Roger Camboulives ZA de Basso Combo",
    cp: "31100",
    ville: "Toulouse",
    departement: "31",
    telephone: "05 61 40 49 18",
    email: "toulouse@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (TOULOUSE)",
    adresse: "HELIOPOLE Bât. D 33-43 avenue Georges Pompidou",
    cp: "31130",
    ville: "Balma",
    departement: "31",
    telephone: "05 61 12 29 70",
    email: "toulouse@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/toulouse-ottobock-orthopedie/",
  },
  {
    nom: "EQUIP' SANTE",
    adresse: "2 rue René Coty",
    cp: "85000",
    ville: "La Roche S/Yon",
    departement: "85",
    telephone: "02 51 37 07 72",
    email: "NC",
    siteWeb: "http://www.equip-sante.com",
  },
  {
    nom: "LAGARRIGUE",
    adresse: "2 Rue René Coty",
    cp: "85000",
    ville: "La Roche-Sur-Yon",
    departement: "85",
    telephone: "02 51 36 09 15",
    email: "larochesuryon@lagarrigue.com",
    siteWeb: "https://lagarrigue.com/",
  },
  {
    nom: "PROTEOR LA ROCHE-SUR-YON",
    adresse: "1 bis rue Haxo",
    cp: "85000",
    ville: "La Roche-Sur-Yon",
    departement: "85",
    telephone: "02 52 43 08 07",
    email: "larochesuryon@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "APPAREILLAGE PROTHESE ORTHOPEDIE",
    adresse: "54 ter avenue Jacques Douzans",
    cp: "31600",
    ville: "Muret",
    departement: "31",
    telephone: "05 62 23 03 44",
  },
  {
    nom: "OXILIUM",
    adresse: "5 Avenue Vialas",
    cp: "81370",
    ville: "Saint Sulpice La Pointe",
    departement: "81",
    telephone: "",
    email: "info@",
    siteWeb: "http://www.oxilium-orthoprothesiste.fr",
  },
  {
    nom: "LAGARRIGUE ALBI",
    adresse: "Rue François Arago",
    cp: "81000",
    ville: "Albi",
    departement: "81",
    telephone: "05 63 45 48 25",
    email: "albi@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "ORTEA",
    adresse: "210, rue des Charpentiers ZA Bel Air",
    cp: "12000",
    ville: "Rodez",
    departement: "12",
    telephone: "",
    email: "info@",
    siteWeb: "http://",
  },
  {
    nom: "AVEYRON ORTHOPEDIE",
    adresse: "6 avenue de Rodez",
    cp: "12510",
    ville: "Olemps",
    departement: "12",
    telephone: "05 65 68 23 42",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (RODEZ)",
    adresse: "5 boulevard Belle Isle",
    cp: "12000",
    ville: "Rodez",
    departement: "12",
    telephone: "05 65 67 31 70",
    email: "rodez@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/rodez-marcenac-ducros/",
  },
  {
    nom: "ALBATROS NANTES",
    adresse: "Parc d'activité de la Bayonne",
    cp: "44140",
    ville: "Montbert",
    departement: "44",
    telephone: "",
    email: "albatros@albatros-france.fr",
    siteWeb: "https://albatros-france.fr",
  },
  {
    nom: "EQUIP'SANTE",
    adresse: "3 rue Blaise Pascal",
    cp: "44400",
    ville: "Reze",
    departement: "44",
    telephone: "02 40 48 55 90",
    email: "NC",
    siteWeb: "http://www.equip-sante.com/",
  },
  {
    nom: "PROTEOR SAUMUR",
    adresse: "Place de Nantilly",
    cp: "49400",
    ville: "Saumur",
    departement: "49",
    telephone: "02 41 51 29 59",
    email: "angers@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "LAGARRIGUE NANTES",
    adresse: "18 Bd Victor Hugo",
    cp: "44200",
    ville: "Nantes",
    departement: "44",
    telephone: "02 40 20 15 82",
    email: "nantes@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "PROTEOR NANTES",
    adresse: "359 route de Sainte Luce Village du petit Chatelier",
    cp: "44301",
    ville: "Nantes",
    departement: "44",
    telephone: "02 51 89 92 43",
    email: "nantes@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "AUDRAIN ORTHO MEDICAL",
    adresse: "97 route de Vannes",
    cp: "44800",
    ville: "Saint Herblain",
    departement: "44",
    telephone: "02 40 76 61 53",
    siteWeb: "https://www.audrain-ortho-medical.fr/",
  },
  {
    nom: "BOP TECHNOLOGIES",
    adresse: "Parc de la Fleuriaye 9 rue Augustin Fresnel",
    cp: "44481",
    ville: "Carquefou",
    departement: "44",
    telephone: "02 40 25 85 18",
    siteWeb: "https://www.bop-technologies.fr",
  },
  {
    nom: "FORMOTION ORTHOPÉDIE",
    adresse: "rue Sylvain Rebrioux",
    cp: "36130",
    ville: "Deols",
    departement: "36",
    telephone: "02 54 07 32 20",
    email: "admin.chateauroux@formotion.com",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "PROTEOR ANGERS",
    adresse: "181 - 183 boulevard de Strasbourg",
    cp: "49000",
    ville: "Angers",
    departement: "49",
    telephone: "02 41 44 20 88",
    email: "angers@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "LAGARRIGUE ANGERS",
    adresse: "16 rue Auguste Gautier",
    cp: "49100",
    ville: "Angers",
    departement: "49",
    telephone: "02 41 25 33 50",
    email: "angers@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "ORTHO-MAINE",
    adresse: "9 rue René Bremont",
    cp: "49100",
    ville: "Angers",
    departement: "49",
    telephone: "02 41 87 99 00",
    siteWeb: "https://www.ortho-maine.fr",
  },
  {
    nom: "LAGARRIGUE",
    adresse: "Espace Paulette - Rte de Bram",
    cp: "11000",
    ville: "Carcassonne",
    departement: "11",
    telephone: "04 68 65 63 22",
    email: "narbonne@groupelagarrigue.com",
    siteWeb: "https://lagarrigue.com/",
  },
  {
    nom: "FORMOTION ORTHOPÉDIE",
    adresse: "22 rue des Frères Lumière",
    cp: "37170",
    ville: "Chambray-Les-Tours",
    departement: "37",
    telephone: "02 47 20 82 56",
    email: "admin.tours@formotion.com",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "ALBATROS TOURS",
    adresse: "16 Ter rue Augustin Fresnel",
    cp: "37170",
    ville: "Chambray-Les-Tours",
    departement: "37",
    telephone: "",
    email: "albatros@albatros-france.fr",
    siteWeb: "https://albatros-france.fr",
  },
  {
    nom: "PROTEOR SAINT NAZAIRE",
    adresse: "24 boulevard de l'Université",
    cp: "44600",
    ville: "Saint Nazaire",
    departement: "44",
    telephone: "02 52 41 07 60",
    email: "saintnazaire@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "LAGARRIGUE SAINT-NAZAIRE",
    adresse: "43 Bd de l'Université",
    cp: "44600",
    ville: "St Nazaire",
    departement: "44",
    telephone: "02 40 43 62 88",
    email: "stnazaire@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "EQUIP'SANTE",
    adresse: "67 avenue Ferdinand de Lesseps",
    cp: "44600",
    ville: "Saint-Nazaire",
    departement: "44",
    telephone: "02 40 53 19 45",
    email: "NC",
    siteWeb: "http://www.equip-sante.com/",
  },
  {
    nom: "PROTEOR TOURS",
    adresse: "18 rue de la Tuilerie",
    cp: "37550",
    ville: "Saint-Avertin",
    departement: "37",
    telephone: "02 47 28 91 59",
    email: "tours@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "PROTEOR NÉRIS-LES-BAINS",
    adresse: "Route de Clermont",
    cp: "03310",
    ville: "Neris Les Bains",
    departement: "03",
    telephone: "04 70 64 35 37",
    email: "neris@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "PROTEOR CLERMONT-FERRANT",
    adresse: "74 avenue Jean Jaurès",
    cp: "63540",
    ville: "Romagnat",
    departement: "63",
    telephone: "04 73 28 44 95",
    email: "clermont@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "LAGARRIGUE CLERMONT-FERRAND",
    adresse: "236 Bd Etienne Clémentel",
    cp: "63100",
    ville: "Clermont-Ferrand",
    departement: "63",
    telephone: "04 73 24 23 23",
    email: "clermontferrant@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (CLERMONT-FERRAND)",
    adresse: "27 route de Cendre ZI des Acilloux",
    cp: "63800",
    ville: "Cournon D'Auvergne",
    departement: "63",
    telephone: "04 73 61 15 91",
    email: "clermont@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/clermont-ferrand-chabloz-orthopedie/",
  },
  {
    nom: "ALBATROS CLERMONT-FERRAND",
    adresse: "9 bis Avenue Pierre et Marie Curie",
    cp: "63360",
    ville: "Gerzat",
    departement: "63",
    telephone: "",
    email: "albatros@albatros-france.fr",
    siteWeb: "https://albatros-france.fr",
  },
  {
    nom: "SOCIETE D'APPAREILLAGE DU CENTRE STER",
    adresse: "10 avenue Dr Jean Ster",
    cp: "34240",
    ville: "Lamalou Les Bains",
    departement: "34",
    telephone: "04 67 95 77 01",
  },
  {
    nom: "COS ORTHO",
    adresse: "3 rue des Filatures",
    cp: "34700",
    ville: "Lodeve",
    departement: "34",
    telephone: "",
    email: "info@",
    siteWeb: "http://",
  },
  {
    nom: "LAGARRIGUE NARBONNE",
    adresse: "110 bis avenue Anatole France",
    cp: "11100",
    ville: "Narbonne",
    departement: "11",
    telephone: "04 68 65 63 21",
    email: "narbonne@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "FORMOTION ORTHOPÉDIE",
    adresse: "2 rue du Docteur Laënnec",
    cp: "18230",
    ville: "Saint Doulchard",
    departement: "18",
    telephone: "02 48 24 94 10",
    email: "admin.bourges@formotion.com",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (NARBONNE)",
    adresse: "ZAC Bonne Source - 12 Rue Ernest Cognacq",
    cp: "11000",
    ville: "Narbonne",
    departement: "11",
    telephone: "",
    email: "narbonne@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/narbonne-marcenac-ducros/",
  },
  {
    nom: "PROTEOR VICHY",
    adresse: "Pôle Médical OYHENART 3 bis rue Doyat",
    cp: "03300",
    ville: "Cusset",
    departement: "03",
    telephone: "04 70 59 23 39",
    email: "vichy@@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "LAGARRIGUE",
    adresse: "20 avenue Jean Moulin",
    cp: "34500",
    ville: "Beziers",
    departement: "34",
    telephone: "04 67 15 35 24",
    email: "montpellier@groupelagarrigue.com",
    siteWeb: "https://lagarrigue.com/",
  },
  {
    nom: "PROTEOR BEZIERS",
    adresse: "283 allée des Charmes",
    cp: "34500",
    ville: "Beziers",
    departement: "34",
    telephone: "04 67 52 47 48",
    email: "beziers@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (BÉZIERS)",
    adresse: "13 Rue du Docteur Flemong - Le Patio - ZAC de Montimarrant",
    cp: "34500",
    ville: "Beziers",
    departement: "34",
    telephone: "",
    email: "beziers@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/beziers-orthese-prothese-changeant/",
  },
  {
    nom: "PROTEOR LE MANS",
    adresse: "22 rue Arnod Dolmetzch",
    cp: "72000",
    ville: "Le Mans",
    departement: "72",
    telephone: "02 43 39 22 90",
    email: "lemans@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "PROTEOR VANNES",
    adresse: "10 rue Dr Joseph Audic Médicentre du Ténénio",
    cp: "56000",
    ville: "Vannes",
    departement: "56",
    telephone: "02 97 62 00 02",
    email: "vannes@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "FORMOTION ORTHOPÉDIE",
    adresse: "10 rue Fernand Soulet",
    cp: "53000",
    ville: "Laval",
    departement: "53",
    telephone: "02 30 30 06 02",
    email: "admin.laval@formotion.com",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "PROTEOR MOULINS",
    adresse: "27 avenue d'Orvilliers La résidence",
    cp: "03000",
    ville: "Moulins",
    departement: "03",
    telephone: "04 70 46 85 46",
    email: "moulins@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "PROTEOR LAVAL",
    adresse: "14 rue Ernest Laurain",
    cp: "53000",
    ville: "Laval",
    departement: "53",
    telephone: "02 43 56 42 45",
    email: "laval@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "FORMOTION ORTHOPÉDIE",
    adresse: "5 rue Victor Duruy",
    cp: "72650",
    ville: "Saint-Saturnin",
    departement: "72",
    telephone: "02 43 14 29 33",
    email: "admin.le-mans@formotion.com",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "BROCHER ORTHOPÉDIE",
    adresse: "9 RUE DE LA TREMBLAIE",
    cp: "72650",
    ville: "La Milesse",
    departement: "72",
    telephone: "02 59 16 27 03",
    email: "contact@brocher-orthopedie.fr",
    siteWeb: "http://www.brocher-orthopedie.fr/",
  },
  {
    nom: "LAGARRIGUE PERPIGNAN",
    adresse: "139 rue Ettore Bugatti Polygone Nord",
    cp: "66000",
    ville: "Perpignan",
    departement: "66",
    telephone: "04 68 61 18 05",
    email: "perpignan@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "PROTEOR PERPIGNAN",
    adresse: "1415 avenue Julien Panchot",
    cp: "66000",
    ville: "Perpignan",
    departement: "66",
    telephone: "04 68 68 33 23",
    email: "perpignan@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (PERPIGNAN)",
    adresse: "2 rue Ernest Renan",
    cp: "66000",
    ville: "Perpignan",
    departement: "66",
    telephone: "04 68 52 84 09",
    email: "perpignan@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/perpignan-marcenac-ducros/",
  },
  {
    nom: "FORMOTION ORTHOPÉDIE",
    adresse: "7 rue du Bois de Soeuvres ZA de la Hallerais",
    cp: "35770",
    ville: "Vern S/Seiche",
    departement: "35",
    telephone: "02 99 86 00 11",
    email: "admin.rennes@formotion.com",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "PROTEOR RENNES",
    adresse: "14 rue de la Rigourdière",
    cp: "35510",
    ville: "Cesson Sevigne",
    departement: "35",
    telephone: "02 99 67 35 34",
    email: "rennes@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (NEVERS)",
    adresse: "31 Boulevard du Pré Plantin",
    cp: "58000",
    ville: "Nevers",
    departement: "58",
    telephone: "03 80 72 01 80",
    email: "nevers@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/agence-nevers/",
  },
  {
    nom: "OPR",
    adresse: "28 avenue des champs blancs",
    cp: "35510",
    ville: "Cesson Sevigne",
    departement: "35",
    telephone: "02 23 20 00 44",
    siteWeb: "http://opr35.com/",
  },
  {
    nom: "LAGARRIGUE RENNES",
    adresse: "3 rue du Coëtlogon",
    cp: "35000",
    ville: "Rennes",
    departement: "35",
    telephone: "02 97 76 50 51",
    email: "rennes@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "SUD ORTHOPEDIE",
    adresse: "849 rue Favre de St Castor",
    cp: "34080",
    ville: "Montpellier",
    departement: "34",
    telephone: "04 67 04 24 15",
    siteWeb: "https://www.sudorthopedie34.fr/",
  },
  {
    nom: "PROTEOR MONTPELLIER",
    adresse: "436 rue de la Croix verte Parc Euromédecine",
    cp: "34196",
    ville: "Montpellier",
    departement: "34",
    telephone: "04 67 52 47 48",
    email: "montpellier@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "LAGARRIGUE MONTPELLIER",
    adresse: "172 rue de la Jasse de Maurin",
    cp: "34070",
    ville: "Montpellier",
    departement: "34",
    telephone: "04 67 15 35 24",
    email: "montpellier@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "SCHAEFFLER ORTHOPEDIE (GROUPE PROTEOR)",
    adresse: "PA du Moulin 2 allée Antoine Petit",
    cp: "45160",
    ville: "Olivet",
    departement: "45",
    telephone: "02 38 44 91 44",
    siteWeb: "http://www.schaefflerorthopedie.fr",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (MONTPELLIER)",
    adresse: "410 rue Etienne Lenoir",
    cp: "34130",
    ville: "Maugio",
    departement: "34",
    telephone: "",
    email: "montpellier@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/montpellier-marcenac-ducros/",
  },
  {
    nom: "ERIC METSU ORTHOPÉDIE",
    adresse: "95 Rue Joseph Aloïs SChumpeter",
    cp: "34470",
    ville: "Perols",
    departement: "34",
    telephone: "",
    email: "info@",
  },
  {
    nom: "JOUVET ORTHOPEDIE",
    adresse: "504 La Mourre",
    cp: "34130",
    ville: "Mauguio",
    departement: "34",
    telephone: "",
    email: "info@",
    siteWeb: "http://",
  },
  {
    nom: "VYV ÉQUIPEMENT MÉDICAL",
    adresse: "41 rue Chaigneau",
    cp: "56100",
    ville: "Lorient",
    departement: "56",
    telephone: "02 97 21 91 81",
    siteWeb: "https://www.harmonie-medical-service.fr/nos-magasins/lorient",
  },
  {
    nom: "FORMOTION ORTHOPÉDIE",
    adresse: "7 rue Jacques Brel",
    cp: "56100",
    ville: "Lorient",
    departement: "56",
    telephone: "02 97 87 07 55",
    email: "admin.lorient@formotion.com",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "PROTEOR LORIENT",
    adresse: "165 rue de la montagne du Salut Bâtiment J2 - Porte 3",
    cp: "56600",
    ville: "Lanester",
    departement: "56",
    telephone: "02 56 54 81 81",
    email: "proteor.lorient@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "LAGARRIGUE CAUDAN",
    adresse: "375 rue Jean Baptiste Martenot ZI Lann Sévelin",
    cp: "56850",
    ville: "Caudan",
    departement: "56",
    telephone: "02 97 76 50 51",
    email: "caudan@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "ORTHOPEDIE GENERALE",
    adresse: "9 rue Jehan de Meung",
    cp: "45000",
    ville: "Orleans",
    departement: "45",
    telephone: "02 38 68 04 49",
    siteWeb: "https://www.orthopedie-bernard.f",
  },
  {
    nom: "PROTEOR SAINT-ETIENNE",
    adresse: "14 rue du Père Thoisy ZI du Devey",
    cp: "42530",
    ville: "Saint-Genest-Lerpt",
    departement: "42",
    telephone: "04 77 57 62 64",
    email: "saintetienne@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "ORTHOPEDIE DU FOREZ",
    adresse: "73 rue de la Talaudière",
    cp: "42000",
    ville: "Saint Etienne",
    departement: "42",
    telephone: "04 77 55 03 78",
    siteWeb: "www.orthoforez.cabanova.com",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (SAINT-ETIENNE)",
    adresse: "800 Bd Jean Rostand",
    cp: "42650",
    ville: "St Jean Bonnefonds",
    departement: "42",
    telephone: "04 77 46 21 26",
    email: "saint-etienne@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/saint-etienne-chabloz-orthopedie/",
  },
  {
    nom: "LAGARRIGUE SAINT-CHAMOND",
    adresse: "Gentialon - 4 allées Copernic",
    cp: "42400",
    ville: "Saint-Chamond",
    departement: "42",
    telephone: "04 77 22 37 68",
    email: "saintetienne@lagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (NÎMES)",
    adresse: "2725 Route de Montpellier",
    cp: "30000",
    ville: "Nîmes",
    departement: "30",
    telephone: "04 66 29 48 85",
    email: "nimes@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/nimes-marcenac-ducros/",
  },
  {
    nom: "LAGARRIGUE NÎMES",
    adresse: "221 rue Nicolas Ledoux Bât. A VALMEDICA 1er étage",
    cp: "30900",
    ville: "Nimes",
    departement: "30",
    telephone: "04 66 29 65 28",
    email: "nimes@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "FORMOTION ORTHOPÉDIE",
    adresse: "ZA du Clavon Rue Louis Braille",
    cp: "26230",
    ville: "Valaurie",
    departement: "26",
    telephone: "04 75 52 99 05",
    email: "admin.valaurie@formotion.com",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "PROTEOR CHARTRES",
    adresse: "56 rue des Comtesses",
    cp: "28000",
    ville: "Chartres",
    departement: "28",
    telephone: "02 43 39 22 90",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (VALENCE)",
    adresse: "ZA Morlon 135, rue Pierre Seghers",
    cp: "26800",
    ville: "Portes-Les-Valence",
    departement: "26",
    telephone: "04 75 40 12 91",
    email: "valence@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/valence-chabloz-orthopedie/",
  },
  {
    nom: "PROTEOR VALENCE",
    adresse: "176 B avenue Victor Hugo",
    cp: "26000",
    ville: "Valence",
    departement: "26",
    telephone: "04 75 40 81 40",
    email: "valence@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "FORMOTION ORTHOPÉDIE",
    adresse: "5 route du Paisy",
    cp: "69570",
    ville: "Dardilly",
    departement: "69",
    telephone: "04 37 64 26 42",
    email: "admin.lyon@formotion.com",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "MATHIS SA",
    adresse: "ZA de Keranguyon",
    cp: "29950",
    ville: "Benodet",
    departement: "29",
    telephone: "02 98 57 21 45",
    siteWeb: "http://www.mathis-ortho.com/",
  },
  {
    nom: "LAGARRIGUE VALENCE",
    adresse: "119 Bd de la Corniche Plateau de Lautagne",
    cp: "26000",
    ville: "Valence",
    departement: "26",
    telephone: "04 28 69 03 80",
    email: "valence@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "FORMOTION ORTHOPÉDIE",
    adresse: "8 Rue du Docteur Abel",
    cp: "26000",
    ville: "Valence",
    departement: "26",
    telephone: "",
    email: "admin.valence@formotion.com",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "PROTEOR VILLEFRANCHE SUR SAÔNE",
    adresse: "120 ancienne route de Beaujeu Bâtiment la Passerelle",
    cp: "69400",
    ville: "Arnas",
    departement: "69",
    telephone: "09 70 75 55 40",
    email: "villefrance@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "ORTHO ACCESS",
    adresse: "19 avenue de l’Aspre",
    cp: "30150",
    ville: "Roquemaure",
    departement: "30",
    telephone: "04 66 50 80 04",
    siteWeb: "http://www.orthoaccess.fr/",
  },
  {
    nom: "ALBATROS VALENCE",
    adresse: "11 rue Jean Bertin",
    cp: "26000",
    ville: "Valence",
    departement: "26",
    telephone: "",
    email: "albatros@albatros-france.fr",
    siteWeb: "https://albatros-france.fr",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (LYON)",
    adresse: "46 avenue Jean Jaurès",
    cp: "69600",
    ville: "Oullins",
    departement: "69",
    telephone: "04 78 50 34 03",
    email: "lyon@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/lyon-chabloz-orthopedie/",
  },
  {
    nom: "ORTHESIS",
    adresse: "1 rue du Chapeau Rouge",
    cp: "69009",
    ville: "Lyon",
    departement: "69",
    telephone: "04 72 53 70 80",
    siteWeb: "https://orthesiste-lyon.com/",
  },
  {
    nom: "PROTEOR SAINT MALO",
    adresse: "4 rue Joséphine Le Scolan",
    cp: "35400",
    ville: "Saint Malo",
    departement: "35",
    telephone: "02 99 40 10 91",
    email: "saintmalo@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "LAGARRIGUE LYON GERLAND",
    adresse: "359 Avenue Jean Jaurès",
    cp: "69007",
    ville: "Lyon",
    departement: "69",
    telephone: "04 78 16 00 89",
    email: "info@",
    siteWeb: "https://lagarrigue.com/",
  },
  {
    nom: "ALBATROS LYON",
    adresse: "113 rue André Bollier",
    cp: "69007",
    ville: "Lyon",
    departement: "69",
    telephone: "04 75 57 66 43",
    email: "albatros@albatros-france.fr",
    siteWeb: "https://albatros-france.fr",
  },
  {
    nom: "FORMOTION ORTHOPÉDIE",
    adresse: "29 bd Trehouart",
    cp: "35400",
    ville: "Saint-Malo",
    departement: "35",
    telephone: "02 23 52 47 02",
    email: "admin.saint-malo@formotion.com",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "LAGARRIGUE TREGUEUX",
    adresse: "44 rue Marc Seguin",
    cp: "22950",
    ville: "Tregueux",
    departement: "22",
    telephone: "02 96 52 49 00",
    email: "tregueux@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "LAGARRIGUE LYON SANTY",
    adresse: "17 avenue Paul Santy",
    cp: "69008",
    ville: "Lyon",
    departement: "69",
    telephone: "NC",
    email: "Lyon@groupelagarrigue.com",
    siteWeb: "https://lagarrigue.com/",
  },
  {
    nom: "LAGARRIGUE AVIGNON",
    adresse: "825 rue de l'Aulanière",
    cp: "84000",
    ville: "Avignon",
    departement: "84",
    telephone: "04 90 16 64 64",
    email: "avignon@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "PROTEOR LYON",
    adresse: "125 rue Bataille",
    cp: "69008",
    ville: "Lyon",
    departement: "69",
    telephone: "04 72 84 77 30",
    email: "lyon@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "FORMOTION ORTHOPÉDIE",
    adresse: "2 allée Benjamin Constant",
    cp: "29200",
    ville: "Quimper",
    departement: "29",
    telephone: "02 98 84 37 16",
    email: "admin.lorient@formotion.com",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "LAGARRIGUE",
    adresse: "13 rue du Président Sadate",
    cp: "29000",
    ville: "Quimper",
    departement: "29",
    telephone: "02 97 76 50 51",
    email: "caudan@groupelagarrigue.com",
    siteWeb: "https://lagarrigue.com/",
  },
  {
    nom: "LAGARRIGUE VAULX-EN-VELIN",
    adresse: "6 rue de Dauphiné",
    cp: "69120",
    ville: "Vaulx-En-Velin",
    departement: "69",
    telephone: "04 78 53 69 37",
    email: "Lyon@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "FORMOTION ORTHOPÉDIE",
    adresse: "4A rue du Bignon - ZA Les Prunelles",
    cp: "22190",
    ville: "Plerin",
    departement: "22",
    telephone: "02 96 52 07 02",
    email: "admin.saint-brieuc@formotion.com",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "PROTEOR PLÉRIN",
    adresse: "1 rue François Jacob",
    cp: "22190",
    ville: "Plerin",
    departement: "22",
    telephone: "02 96 52 42 06",
    email: "plerin@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (MÂCON)",
    adresse: "109, allée Joanny Mommessin",
    cp: "71850",
    ville: "Charnay Les Mâcon",
    departement: "71",
    telephone: "03 85 38 51 48",
    email: "macon@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/agence-macon/",
  },
  {
    nom: "LAGARRIGUE GRANVILLE",
    adresse: "Chemin de la Lande",
    cp: "50400",
    ville: "Yquelon",
    departement: "50",
    telephone: "02 21 00 06 30",
    email: "granville@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "FORMOTION",
    adresse: "5 avenue du Maréchal Leclerc",
    cp: "50400",
    ville: "Granville",
    departement: "50",
    telephone: "02 31 72 82 54",
    email: "admin.caen@formotion.com",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (AVIGNON)",
    adresse: "43 Départementale 7 - Nationale gauche",
    cp: "13670",
    ville: "Saint Andiol",
    departement: "13",
    telephone: "",
    email: "avignon@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/avignon-marcenac-ducros/",
  },
  {
    nom: "LAGARRIGUE",
    adresse: "118 Rue de la Croix Colin",
    cp: "01750",
    ville: "Replonges",
    departement: "01",
    telephone: "04 28 69 06 20",
    email: "macon@groupelagarrigue.com",
    siteWeb: "https://lagarrigue.com/",
  },
  {
    nom: "NEUT",
    adresse: "37 rue Paul Bert",
    cp: "89000",
    ville: "Auxerre",
    departement: "89",
    telephone: "03 25 76 71 74",
    email: "info@",
    siteWeb: "http://",
  },
  {
    nom: "PROTEOR CHALON-SUR SAÔNE",
    adresse: "76 rue d'Autun",
    cp: "71100",
    ville: "Chalon-Sur-Saone",
    departement: "71",
    telephone: "06 85 93 67 79",
    email: "chalon@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "LAGARRIGUE SALON DE PROVENCE",
    adresse: "71 rue de la Forge",
    cp: "13300",
    ville: "Salon De Provence",
    departement: "13",
    telephone: "04 91 43 09 25",
    email: "salondeprovence@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "FORMOTION ORTHOPÉDIE",
    adresse: "12 Rue de l'Orme Brise",
    cp: "77310",
    ville: "Pringy",
    departement: "77",
    telephone: "01 64 09 96 82",
    email: "admin.antony@formotion.com",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "NEUT",
    adresse: "3 impasse Saint Vincent",
    cp: "89100",
    ville: "St Denis Les Sens",
    departement: "89",
    telephone: "03 86 64 94 23",
    email: "info@",
    siteWeb: "http://",
  },
  {
    nom: "LAGARRIGUE AGNEAUX",
    adresse: "4 Rue du Général de Gaulle",
    cp: "50180",
    ville: "Agneaux",
    departement: "50",
    telephone: "02 35 55 64 64",
    email: "info@",
    siteWeb: "https://lagarrigue.com/",
  },
  {
    nom: "POMMIER ORTHOPEDIE",
    adresse: "ZA de Courtaboeuf Avenue du Groenland",
    cp: "91140",
    ville: "Villebon S/Yvette",
    departement: "91",
    telephone: "01 60 92 04 40",
    siteWeb: "https://www.pommier-orthopedie.com/",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (AMBÉRIEU)",
    adresse: "255 Impasse des Perdrix",
    cp: "01500",
    ville: "Chateau-Gaillard",
    departement: "01",
    telephone: "04 37 86 46 55",
    email: "amberieu@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/amberieu-ottobock-orthopedie/",
  },
  {
    nom: "ESPACE ORTHOPEDIQUE",
    adresse: "20 avenue des sports",
    cp: "01000",
    ville: "Bourg En Bresse",
    departement: "01",
    telephone: "04 74 21 19 00",
    siteWeb: "http://www.proteor.fr/",
  },
  {
    nom: "PROTEOR MELUN",
    adresse: "35 boulevard Aristide Briand Résidence la Pléiade",
    cp: "77000",
    ville: "Melun",
    departement: "77",
    telephone: "01 64 09 42 18",
    email: "melun@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "LAGARRIGUE CAEN",
    adresse: "2D rue du long Douet",
    cp: "14760",
    ville: "Bretteville Sur Odon",
    departement: "14",
    telephone: "02 21 00 06 30",
    email: "caen@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "LAGARRIGUE",
    adresse: "6 bis rue Jean Jaurès",
    cp: "29600",
    ville: "Morlaix",
    departement: "29",
    telephone: "02 98 41 44 61",
    email: "brest@groupelagarrigue.com",
    siteWeb: "https://lagarrigue.com/",
  },
  {
    nom: "FORMOTION ORTHOPÉDIE",
    adresse: "1 rue de la Cotonnière",
    cp: "14000",
    ville: "Caen",
    departement: "14",
    telephone: "02 31 72 82 54",
    email: "admin.caen@formotion.com",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "FORMOTION ORTHOPÉDIE",
    adresse: "SILIC 26 17 rue Georges Besse",
    cp: "92160",
    ville: "Antony",
    departement: "92",
    telephone: "01 46 78 08 08",
    email: "admin.antony@formotion.com",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "NEUT",
    adresse: "9 rue de l’orangerie",
    cp: "78000",
    ville: "Versailles",
    departement: "78",
    telephone: "01 39 51 61 40",
    email: "info@",
    siteWeb: "http://",
  },
  {
    nom: "PROTEOR VERSAILLES",
    adresse: "5 résidence de la Petite Place",
    cp: "78000",
    ville: "Versailles",
    departement: "78",
    telephone: "01 39 55 45 38",
    email: "proteor.versailles@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "PROTEOR CAEN",
    adresse: "571 rue Marie Curie CITIS",
    cp: "14200",
    ville: "Herouville-Saint-Clair",
    departement: "14",
    telephone: "02 31 15 58 58",
    email: "caen@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE & SERVICES - OTTOBOCK (CARE YERRES)",
    adresse: "37 rue Raymond Poincaré",
    cp: "91330",
    ville: "Yerres",
    departement: "91",
    telephone: "01 69 48 59 03",
    email: "yerres@ottobock.com",
    siteWeb: "https://www.laprothesegenerale.fr",
  },
  {
    nom: "PROTEOR BREST",
    adresse: "465 rue Jurien de la Gravière",
    cp: "29200",
    ville: "Brest",
    departement: "29",
    telephone: "02 90 82 84 74",
    email: "proteor.brest2@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (GRENOBLE)",
    adresse: "2A avenue Pierre de Coubertin",
    cp: "38170",
    ville: "Seyssinet-Pariset",
    departement: "38",
    telephone: "04 38 26 02 02",
    email: "grenoble@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/agence-grenoble/",
  },
  {
    nom: "PROTEOR PARIS 16",
    adresse: "18 rue Parent de Rosan",
    cp: "75016",
    ville: "Paris",
    departement: "75",
    telephone: "01 40 50 26 39",
    email: "paris16@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "AMBROIS ORTHOPEDIE",
    adresse: "32 bis rue de la Liberté",
    cp: "38600",
    ville: "Fontaine",
    departement: "38",
    telephone: "04 76 26 97 97",
    email: "ambrois-orthopedie@lagarrigue.com",
    siteWeb: "http://www.ambroisorthopedie.fr",
  },
  {
    nom: "LAGARRIGUE GENTILLY",
    adresse: "48 avenue Raspail",
    cp: "94250",
    ville: "Gentilly",
    departement: "94",
    telephone: "01 47 40 91 92",
    email: "gentilly@ravier-touzard.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "BOP TECHNOLOGIES PARIS",
    adresse: "15 rue Leriche",
    cp: "75015",
    ville: "Paris",
    departement: "75",
    telephone: "02 40 25 85 18",
    email: "info@",
    siteWeb: "http://",
  },
  {
    nom: "ORTHONOMY",
    adresse: "3 Rue Missak Manouchian",
    cp: "38130",
    ville: "Echirolles",
    departement: "38",
    telephone: "04.56.59.93.75",
    email: "contact@orthonomy.fr",
    siteWeb: "https://orthonomy.fr/",
  },
  {
    nom: "OUEST ORTHOPEDIE",
    adresse: "540 rue Augustin Jacq",
    cp: "29200",
    ville: "Brest",
    departement: "29",
    telephone: "02 98 43 08 58",
    siteWeb: "http://ouest-orthopedie.com/",
  },
  {
    nom: "PROTEOR PARIS 13 (ORTHÈSES)",
    adresse: "21 - 25 rue Albert",
    cp: "75013",
    ville: "Paris",
    departement: "75",
    telephone: "01 45 86 63 63",
    email: "paris@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "ORTHOVISION",
    adresse: "3 villa de l’Astrolabe",
    cp: "75015",
    ville: "Paris",
    departement: "75",
    telephone: "01 40 56 02 20",
  },
  {
    nom: "AHP EUROPE",
    adresse: "39 rue Carnot",
    cp: "94700",
    ville: "Maisons-Alfort",
    departement: "94",
    telephone: "01 55 96 05 40",
    siteWeb: "https://www.ahp-europe.com",
  },
  {
    nom: "LAGARRIGUE BREST",
    adresse: "10 rue Amiral Romain Desfosses",
    cp: "29200",
    ville: "Brest",
    departement: "29",
    telephone: "02 98 41 44 61",
    email: "brest@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "PROTEOR PARIS 13 (PROTHÈSES)",
    adresse: "6 rue de Reims",
    cp: "75013",
    ville: "Paris",
    departement: "75",
    telephone: "01 45 83 76 50",
    email: "proteor.paris2@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "LAGARRIGUE AIX-EN-PROVENCE",
    adresse: "9 allée des informaticiens",
    cp: "13290",
    ville: "Aix-En-Provence",
    departement: "13",
    telephone: "04 91 43 09 25",
    email: "aixenprovence@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "ESPACE ORTHO SCOLIOSE",
    adresse: "1 rue Jacques Cœur",
    cp: "75004",
    ville: "Paris",
    departement: "75",
    telephone: "01 44 78 94 84",
    siteWeb: "https://www.espace-ortho-scoliose.fr",
  },
  {
    nom: "DEMEURE ORTHOPEDIE (GROUPE PROTEOR)",
    adresse: "1 rue Rosa Lee Parks",
    cp: "38400",
    ville: "St Martin D'Heres",
    departement: "38",
    telephone: "04 76 54 15 02",
    siteWeb: "http://www.demeureorthopedie.fr",
  },
  {
    nom: "NEUT",
    adresse: "9 rue Léopold Bellan",
    cp: "75002",
    ville: "Paris",
    departement: "75",
    telephone: "01 42 33 83 46",
    siteWeb: "https://www.neut.fr/fr/",
  },
  {
    nom: "PROTEOR PARIS 17",
    adresse: "18 rue Boursault",
    cp: "75017",
    ville: "Paris",
    departement: "75",
    telephone: "01 42 93 92 10",
    email: "paris17@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "OTTO BOCK RÉSEAU ORTHOPÉDIE & SERVICES (AIX-EN-PROVENCE)",
    adresse: "2 Impasse de la Source",
    cp: "13770",
    ville: "Venelles",
    departement: "13",
    telephone: "",
    email: "info@",
    siteWeb: "http://",
  },
  {
    nom: "PROTEOR NOGENT-SUR-MARNE",
    adresse: "6 rue Coulmiers",
    cp: "94130",
    ville: "Nogent-Sur-Marne",
    departement: "94",
    telephone: "01 48 72 96 81",
    email: "nogent@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "LAGARRIGUE CLICHY (ORTHÈSES)",
    adresse: "131, Bd Victor Hugo",
    cp: "92110",
    ville: "Clichy",
    departement: "92",
    telephone: "01 49 68 82 46",
    email: "clichy@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "LAGARRIGUE CLICHY (PROTHÈSES)",
    adresse: "136 Bd Victor Hugo",
    cp: "92110",
    ville: "Clichy",
    departement: "92",
    telephone: "01 49 68 00 97",
    email: "clichy@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (PARIS)",
    adresse: "2 Rue Sigmund Freud Bâtiment Yvoire",
    cp: "75019",
    ville: "Paris",
    departement: "75",
    telephone: "01 42 03 20 30",
    email: "paris19@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/agence-paris/",
  },
  {
    nom: "PROTEOR ROSCOFF",
    adresse: "Centre de Perharidy Centre Hélio-Marin",
    cp: "29680",
    ville: "Roscoff",
    departement: "29",
    telephone: "02 98 29 39 55",
    email: "roscoff@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "ORTHOTECH",
    adresse: "5 rue des artisans",
    cp: "93160",
    ville: "Noisy-Le-Grand",
    departement: "93",
    telephone: "01 48 85 60 50",
    siteWeb: "https://orthotech.fr/",
  },
  {
    nom: "BTC ORTHOPEDIE",
    adresse: "11 rue Neuve Ste Catherine",
    cp: "13007",
    ville: "Marseille",
    departement: "13",
    telephone: "04 91 54 01 88",
    siteWeb: "http://btc-orthopedie.com/",
  },
  {
    nom: "EUROPE ORTHO",
    adresse: "9 rue du Général de Gaulle",
    cp: "76500",
    ville: "Elbeuf",
    departement: "76",
    telephone: "02 35 81 92 39",
  },
  {
    nom: "DUPONT ORTHOPEDIE (GROUPE PROTEOR)",
    adresse: "145 Rue de la Division Leclercq",
    cp: "93350",
    ville: "Le Bourget",
    departement: "93",
    telephone: "01 48 37 88 15",
    email: "lebourget@dupontortho.fr",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "CENTRE D'ORTHOPEDIE APPLIQUEE",
    adresse: "145, av de la division Leclerc",
    cp: "93350",
    ville: "Le Bourget",
    departement: "93",
    telephone: "01 48 37 88 15",
  },
  {
    nom: "LAGARRIGUE MARSEILLE",
    adresse: "240 avenue des Poilus",
    cp: "13012",
    ville: "Marseille",
    departement: "13",
    telephone: "04 91 21 00 70",
    email: "marseille@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "LAGARRIGUE",
    adresse: "59 Aevenue Roland Carraz",
    cp: "21300",
    ville: "Chenove",
    departement: "21",
    telephone: "03 84 82 67 11",
    email: "accueildole@groupelagarrigue.com",
    siteWeb: "https://lagarrigue.com/",
  },
  {
    nom: "PROTEOR MARSEILLE",
    adresse: "25 boulevard Saint Marcel",
    cp: "13011",
    ville: "Marseille",
    departement: "13",
    telephone: "04 91 79 32 44",
    email: "marseille@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "PROTEOR CHAMBERY",
    adresse: "1197 Avenue du Grand Arietaz",
    cp: "73000",
    ville: "Chambery",
    departement: "73",
    telephone: "04 79 85 71 21",
    email: "chambery@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "PROTEOR DIJON",
    adresse: "5 boulevard Winston Churchill ZAC les Hauts de Pouilly",
    cp: "21000",
    ville: "Dijon",
    departement: "21",
    telephone: "03 80 78 42 00",
    email: "dijon@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (MARSEILLE)",
    adresse: "820 Chemin de l'Aumône Vielle",
    cp: "13400",
    ville: "Aubagne",
    departement: "13",
    telephone: "",
    email: "marseille@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/marseille-chabloz-orthopedie/",
  },
  {
    nom: "ORTHONOMY",
    adresse: "350 Rue du Clapet",
    cp: "73490",
    ville: "La Ravoire",
    departement: "73",
    telephone: "04.56.59.93.75",
    email: "contact@orthonomy.fr",
    siteWeb: "https://orthonomy.fr/",
  },
  {
    nom: "LAGARRIGUE LONS-LE-SAUNIER",
    adresse: "205 rue Regard",
    cp: "39000",
    ville: "Lons-Le-Saunier",
    departement: "39",
    telephone: "03 81 48 25 55",
    email: "besancon@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (DIJON)",
    adresse: "30 rue de la Redoute",
    cp: "21850",
    ville: "Saint Appolinaire",
    departement: "21",
    telephone: "03 80 72 01 80",
    email: "dijon@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/agence-dijon/",
  },
  {
    nom: "PROTEOR LONS-LE-SAUNIER",
    adresse: "11 bis avenue du Stade La Tannerie",
    cp: "39000",
    ville: "Lons-Le-Saunier",
    departement: "39",
    telephone: "04 84 25 91 86",
    email: "lons@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "NEUT",
    adresse: "159 avenue d’Echenilly",
    cp: "10120",
    ville: "Saint Andre Les Vergers",
    departement: "10",
    telephone: "03 25 76 10 10",
    email: "info@",
    siteWeb: "http://",
  },
  {
    nom: "PROTEOR LE HAVRE",
    adresse: "45 Rue Paul Doumer",
    cp: "76600",
    ville: "Le Havre",
    departement: "76",
    telephone: "02 35 41 71 71",
    email: "lehaver@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "FORMOTION ORTHOPÉDIE",
    adresse: "3 Chemin des Croix",
    cp: "10430",
    ville: "Rosieres Pres Troyes",
    departement: "10",
    telephone: "03 51 25 20 40",
    email: "admin.troyes@formotion.com",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "LAGARRIGUE TROYES",
    adresse: "6 Rue Jean Monnet 168 ZA Savipol",
    cp: "10300",
    ville: "Sainte-Savine",
    departement: "10",
    telephone: "NC",
    email: "troyes@groupelagarrigue.com",
    siteWeb: "https://lagarrigue.com/",
  },
  {
    nom: "LAGARRIGUE AUBAGNE",
    adresse: "1085 avenue des Paluds",
    cp: "13400",
    ville: "Aubagne",
    departement: "13",
    telephone: "04 91 43 09 25",
    email: "aubagne@groupelagarrigue.cm",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "LAGARRIGUE LE HAVRE",
    adresse: "Zone d'aménagement concerté Nord Bléville Pressoir 80 et 82",
    cp: "76620",
    ville: "Le Havre",
    departement: "76",
    telephone: "02 35 55 64 64",
    email: "info@",
    siteWeb: "https://lagarrigue.com/",
  },
  {
    nom: "ALBATROS MARSEILLE",
    adresse: "115 avenue de la carrière",
    cp: "13830",
    ville: "Roquefort-La-Bedoule",
    departement: "13",
    telephone: "04 42 98 41 97",
    email: "albatros@albatros-france.fr",
    siteWeb: "https://albatros-france.fr",
  },
  {
    nom: "PROTEOR GAP",
    adresse: "7 route de Saint-Jean",
    cp: "05000",
    ville: "Gap",
    departement: "05",
    telephone: "04 13 19 12 11",
    email: "gap@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "PROTEOR ROUEN",
    adresse: "29 rue Louis Blanc",
    cp: "76100",
    ville: "Rouen",
    departement: "76",
    telephone: "02 35 88 17 25",
    email: "rouen@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (GAP)",
    adresse: "27 avenue du Commandant Dumont",
    cp: "05000",
    ville: "Gap",
    departement: "05",
    telephone: "04 38 26 02 02",
    email: "gap@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/gap-chabloz-orthopedie/",
  },
  {
    nom: "FORMOTION ORTHOPÉDIE",
    adresse: "15 rue Saint Gilles",
    cp: "76000",
    ville: "Rouen",
    departement: "76",
    telephone: "02 32 08 08 32",
    email: "admin.rouen@formotion.com",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "NEUT",
    adresse: "8 bis rue des Cordeliers",
    cp: "77100",
    ville: "Meaux",
    departement: "77",
    telephone: "01 60 24 70 89",
    email: "info@",
    siteWeb: "http://",
  },
  {
    nom: "GB ORTHO",
    adresse: "25 Rur Abbé Floquet",
    cp: "76420",
    ville: "Bihorel",
    departement: "76",
    telephone: "06 29 05 10 67",
    email: "baskakoffgerard@gmx.fr",
    siteWeb: "https://gb-ortho.fr/",
  },
  {
    nom: "ORTHEA",
    adresse: "14 avenue des quatre cantons",
    cp: "76000",
    ville: "Rouen",
    departement: "76",
    telephone: "02 35 75 34 00",
    email: "rouen@lagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "LAGARRIGUE DOLE",
    adresse: "10 rue Henri Jean renaud",
    cp: "39100",
    ville: "Dole",
    departement: "39",
    telephone: "03 84 82 67 11",
    email: "accueildole@groupelagarrigue.com",
    siteWeb: "https://www.lagarrigue.com/",
  },
  {
    nom: "ORTHONOMY",
    adresse: "80 Rue des creuses",
    cp: "74960",
    ville: "Cran-Gevrier",
    departement: "74",
    telephone: "04.56.59.93.75",
    email: "contact@orthonomy.fr",
    siteWeb: "https://orthonomy.fr/",
  },
  {
    nom: "ALPES ORTHOPEDIE",
    adresse: "Cran Gevrier - 17 Impasse des Fusains",
    cp: "74960",
    ville: "Annecy",
    departement: "74",
    telephone: "04 50 67 41 36",
    siteWeb: "https://www.alpes-orthopedie-annecy.fr/",
  },
  {
    nom: "PROTEOR ANNECY",
    adresse: "Allée de Mandallaz",
    cp: "74000",
    ville: "Annecy",
    departement: "74",
    telephone: "04 79 36 45 84",
    email: "annecy@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (ANNECY)",
    adresse: "275 route Impériale, Saint Martin de Bellevue",
    cp: "74370",
    ville: "Filliere",
    departement: "74",
    telephone: "04 50 23 24 07",
    email: "annecy@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/annecy-chabloz-orthopedie/",
  },
  {
    nom: "PROTEOR CHERBOURG",
    adresse: "5 rue Noyon",
    cp: "50100",
    ville: "Cherbourg",
    departement: "50",
    telephone: "02 33 22 59 05",
    email: "cherbourg@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "LAGARRIGUE",
    adresse: "55 route des Contamines",
    cp: "74370",
    ville: "Argonay",
    departement: "74",
    telephone: "04 28 69 06 92",
    email: "annecy@groupelagarrigue.com",
    siteWeb: "https://lagarrigue.com/",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (BESANÇON)",
    adresse: "Chemin de l'Etang",
    cp: "25870",
    ville: "Chatillon-Le-Duc",
    departement: "25",
    telephone: "03 81 56 36 49",
    email: "besancon@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/agence-besancon/",
  },
  {
    nom: "BTC ORTHOPEDIE VAR",
    adresse: "Route de la Seyne Batiment K Technopole Var matin",
    cp: "83190",
    ville: "Ollioules",
    departement: "83",
    telephone: "04 94 22 11 83",
    siteWeb: "http://btc-orthopedie.com/",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (ANNEMASSE)",
    adresse: "4 Rue des Artisans",
    cp: "74100",
    ville: "Vetraz-Monthoux",
    departement: "74",
    telephone: "",
    email: "annemasse@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/annemasse-chabloz-orthopedie/",
  },
  {
    nom: "FORMOTION ORTHOPÉDIE",
    adresse: "Rue de Belloy",
    cp: "60860",
    ville: "Saint-Omer-En-Chaussee",
    departement: "60",
    telephone: "03 65 61 10 10",
    email: "admin.beauvais@formotion.com",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "MONT-BLANC ORTHOPEDIE",
    adresse: "615 rue Saint Maurice",
    cp: "74800",
    ville: "Saint Pierre En Faucigny",
    departement: "74",
    telephone: "04 50 03 74 33",
  },
  {
    nom: "LAGARRIGUE TOULON",
    adresse: "10 avenue Gilles de Gennes",
    cp: "83160",
    ville: "La Valette-Du-Var",
    departement: "83",
    telephone: "04 94 00 31 58",
    email: "toulon@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "PROTEOR CARQUEIRANNE",
    adresse: "ZAC les Castors route de la Moutonne",
    cp: "83320",
    ville: "Carqueiranne",
    departement: "83",
    telephone: "04 94 48 28 92",
    email: "carqueiranne@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "AZUR ORTHOPEDIE",
    adresse: "Quartier Le Beau Veze",
    cp: "83320",
    ville: "Carqueiranne",
    departement: "83",
    telephone: "04 94 48 28 92",
    siteWeb: "http://orthopedie.proteor.fr/",
  },
  {
    nom: "BETEILLE ORTHOPEDIE",
    adresse: "38 avenue des Iles d’or",
    cp: "83400",
    ville: "Hyeres",
    departement: "83",
    telephone: "04 94 35 35 07",
    siteWeb: "https://beteille-orthopedie.com",
  },
  {
    nom: "PROTEOR BESANÇON",
    adresse: "10 rue Alfred de Vigny ZAC Lafayette",
    cp: "25000",
    ville: "Besancon",
    departement: "25",
    telephone: "03 81 41 54 54",
    email: "besancon@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "LAGARRIGUE BESANÇON",
    adresse: "33 chemin des Tilleroyes",
    cp: "25000",
    ville: "Besancon",
    departement: "25",
    telephone: "03 81 48 25 55",
    email: "besancon@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "PROTEOR AMIENS",
    adresse: "1 allée de la Pépinière Bâtiment Passiflore - Centre Oasis Dury",
    cp: "80000",
    ville: "Amiens",
    departement: "80",
    telephone: "03 22 50 37 60",
    email: "amiens@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "ORTHOROBS",
    adresse: "2 rue Jean-Nicolas Corvisart (Rue du Campus) ZAC Intercampus",
    cp: "80000",
    ville: "Amiens",
    departement: "80",
    telephone: "03 22 52 58 07",
    email: "orthorobs@gmail.com",
    siteWeb: "https://lagarrigue.com/",
  },
  {
    nom: "LAGARRIGUE REIMS",
    adresse: "34 avenue Hoche",
    cp: "51100",
    ville: "Reims",
    departement: "51",
    telephone: "03 26 09 65 73",
    email: "reims@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "PROTEOR REIMS",
    adresse: "rue Robert Fulton Zone Industrielle Farman",
    cp: "51100",
    ville: "Reims",
    departement: "51",
    telephone: "03 26 47 49 29",
    email: "reims@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "VAR ORTHOPEDIK SERVICES",
    adresse: "266 via Nova",
    cp: "83600",
    ville: "Frejus",
    departement: "83",
    telephone: "04 94 40 32 76",
  },
  {
    nom: "PROTEOR SAINT QUENTIN",
    adresse: "98 bis rue Henriette Cabot",
    cp: "02100",
    ville: "Saint Quentin",
    departement: "02",
    telephone: "03 23 67 67 39",
    email: "proteor.saintquentin@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "LAGARRIGUE NICE",
    adresse: "173 chemin des Iscles ZI SAINT-LAURENT DU VAR",
    cp: "06730",
    ville: "Saint-Laurent Du Var",
    departement: "06",
    telephone: "04 93 27 07 41",
    email: "nice@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (NICE)",
    adresse: "468 bd de la Madeleine",
    cp: "06000",
    ville: "Nice",
    departement: "06",
    telephone: "04 89 14 13 55",
    email: "nice@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/nice-chabloz-orthopedie/",
  },
  {
    nom: "MODAP ORTHOPEDIE (GROUPE PROTEOR)",
    adresse: "32 rue Smolett",
    cp: "06300",
    ville: "Nice",
    departement: "06",
    telephone: "04 93 89 10 20",
    siteWeb: "http://www.modap-orthopedie.com",
  },
  {
    nom: "MIGNARD",
    adresse: "11 avenue du Général de Gaulle",
    cp: "62600",
    ville: "Berck Sur Mer",
    departement: "62",
    telephone: "03 21 09 01 07",
    siteWeb: "http://www.mignard.fr/emploi.htm",
  },
  {
    nom: "LAGARRIGUE MONTBELLIARD",
    adresse: "14 rue André Boulloche",
    cp: "25200",
    ville: "Montbeliard",
    departement: "25",
    telephone: "03 84 82 67 11",
    email: "accueildole@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "ETS. BOUBET",
    adresse: "1750 route de Berck",
    cp: "62180",
    ville: "Rang Du Fliers",
    departement: "62",
    telephone: "03 21 84 44 50",
  },
  {
    nom: "ALBATROS NORD DE FRANCE",
    adresse: "5010 Chemin des Poissonniers",
    cp: "62140",
    ville: "Marconelle",
    departement: "62",
    telephone: "03 21 05 62 11",
    email: "albatros@albatros-france.fr",
    siteWeb: "https://albatros-france.fr",
  },
  {
    nom: "ORTHOPEDIE MENEGHETTI",
    adresse: "1 avenue François Mitterand",
    cp: "62217",
    ville: "Beaurains",
    departement: "62",
    telephone: "03 21 73 45 75",
    siteWeb: "https://www.orthopedie-arras.com/",
  },
  {
    nom: "PROTEOR EPINAL",
    adresse: "1 Allée des Chênes Bât. A",
    cp: "88000",
    ville: "Epinal",
    departement: "88",
    telephone: "03 83 85 41 41",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "FORMOTION ORTHOPÉDIE",
    adresse: "58 avenue Winston Churchill",
    cp: "62000",
    ville: "Arras",
    departement: "62",
    telephone: "03 21 24 83 79",
    email: "admin.arras@formotion.com",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "FORMOTION ORTHOPÉDIE",
    adresse: "60 avenue de Valenciennes",
    cp: "59400",
    ville: "Cambrai",
    departement: "59",
    telephone: "03 27 81 41 75",
    email: "admin.cambrai@formotion.com",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "H2 ORTHOPEDIE",
    adresse: "7 rue Alfred Kastler",
    cp: "54320",
    ville: "Maxeville",
    departement: "54",
    telephone: "03 83 95 15 01",
  },
  {
    nom: "PROTEOR NANCY",
    adresse: "109 avenue de Strasbourg",
    cp: "54000",
    ville: "Nancy",
    departement: "54",
    telephone: "03 83 85 41 41",
    email: "nancy@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "PROTEOR LIEVIN",
    adresse: "175 rue Jean-Baptiste Defernez",
    cp: "62800",
    ville: "Lievin",
    departement: "62",
    telephone: "03 20 04 41 71",
    email: "lievin@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "FORMOTION ORTHOPÉDIE",
    adresse: "238 rue de Brebières",
    cp: "59500",
    ville: "Douai",
    departement: "59",
    telephone: "03 27 88 19 60",
    email: "admin.douai@formotion.com",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "FORMOTION ORTHOPÉDIE",
    adresse: "64 Rue Jean Souvraz",
    cp: "62300",
    ville: "Lens",
    departement: "62",
    telephone: "03 21 28 59 06",
    email: "admin.lens@formotion.com",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (NANCY)",
    adresse: "Zone artisanale du haut Serroir",
    cp: "54690",
    ville: "Lay St Christophe",
    departement: "54",
    telephone: "03 83 32 97 29",
    email: "nancy@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/nancy-technicortho/",
  },
  {
    nom: "PROTEOR LENS",
    adresse: "5 Rue de l'Europe",
    cp: "62300",
    ville: "Lens",
    departement: "62",
    telephone: "03 20 04 41 71",
    email: "lille@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "LAGARRIGUE CHARLEVILLE-MÉZIÈRES",
    adresse: "7 rue des Hautes Chaussées",
    cp: "08000",
    ville: "Charleville-Mezieres",
    departement: "08",
    telephone: "03 24 54 05 05",
    email: "NC",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "DUPONT ORTHOPEDIE (GROUPE PROTEOR)",
    adresse: "249 Place Maréchal Joffre",
    cp: "62400",
    ville: "Bethune",
    departement: "62",
    telephone: "03 21 57 53 33",
    email: "dunkerque@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "LAGARRIGUE (ACMTO)",
    adresse: "9 rue d'Espagne - Parc Secoïa",
    cp: "68310",
    ville: "Wittelsheim",
    departement: "68",
    telephone: "03 89 61 63 20",
    email: "NC",
    siteWeb: "https://lagarrigue.com/",
  },
  {
    nom: "A.C.M.T.O.",
    adresse: "9 rue d'Espagne \"Parc Sécoïa\"",
    cp: "68310",
    ville: "Wittelsheim",
    departement: "68",
    telephone: "03 89 61 63 20",
  },
  {
    nom: "PROTEOR MULHOUSE",
    adresse: "74 rue Jean Monnet West Park",
    cp: "68200",
    ville: "Mulhouse",
    departement: "68",
    telephone: "03 89 34 12 82",
    email: "mulhouse@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "FORMOTION ORTHOPÉDIE",
    adresse: "2 Pont Villars",
    cp: "59300",
    ville: "Valenciennes",
    departement: "59",
    telephone: "03 27 42 01 55",
    email: "admin.valenciennes@formotion.com",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "FORMOTION ORTHOPÉDIE",
    adresse: "97 avenue de France",
    cp: "59600",
    ville: "Maubeuge",
    departement: "59",
    telephone: "03 27 42 01 55",
    email: "admin.valenciennes@formotion.com",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "FORMOTION ORTHOPÉDIE",
    adresse: "311 avenue Eugène Avinée",
    cp: "59120",
    ville: "Loos",
    departement: "59",
    telephone: "03 20 62 99 00",
    email: "admin.loos@formotion.com",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "ORTHOPROJECT LOOS",
    adresse: "85 rue Nelson Mandela",
    cp: "59120",
    ville: "Loos",
    departement: "59",
    telephone: "03 28 01 04 12",
    siteWeb: "https://www.orthoway.fr/le-reseau/",
  },
  {
    nom: "THOUVENY ORTHOPEDIE",
    adresse: "69, Gustave Delory",
    cp: "59810",
    ville: "Lesquin",
    departement: "59",
    telephone: "",
    siteWeb: "http://orthoway.fr",
  },
  {
    nom: "LAGARRIGUE LILLE",
    adresse: "235 rue Faidherbe",
    cp: "59120",
    ville: "Loos",
    departement: "59",
    telephone: "03 20 31 05 58",
    email: "lille@groupelagarrigue.com",
    siteWeb: "http://www.lagarrigue.com/",
  },
  {
    nom: "PROTEOR VILLENEUVE-D'ASCQ",
    adresse: "197 Boulevard de Valmy",
    cp: "59650",
    ville: "Villeneuve-D'Ascq",
    departement: "59",
    telephone: "03 20 04 41 71",
    email: "lille@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "OPFM",
    adresse: "Rue du Houblon",
    cp: "59270",
    ville: "Meteren",
    departement: "59",
    telephone: "06 59 65 45 08",
  },
  {
    nom: "OTTOBOCK RÉSEAU ORTHOPÉDIE ET SERVICES (METZ)",
    adresse: "7 rue Gaston Ramon",
    cp: "57050",
    ville: "Metz",
    departement: "57",
    telephone: "03 83 32 97 29",
    email: "metz@ottobock.com",
    siteWeb: "https://ottobock-ortho.fr/centres-dappareillage/agence-metz/",
  },
  {
    nom: "PROTEOR METZ",
    adresse: "24 La Tannerie",
    cp: "57070",
    ville: "Saint-Julien-Les-Metz",
    departement: "57",
    telephone: "03 87 74 41 32",
    email: "metz@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "FORMOTION ORTHOPÉDIE",
    adresse: "2173 boulevard des Justes",
    cp: "62100",
    ville: "Calais",
    departement: "62",
    telephone: "03 21 96 09 09",
    email: "admin.calais@formotion.com",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "ORTHO MEDICAL WELTER",
    adresse: "4 rue de Ribeauvillé",
    cp: "68180",
    ville: "Horbourg-Wihr",
    departement: "68",
    telephone: "03 89 24 24 07",
    siteWeb: "http://www.orthomedicalwelter.fr/",
  },
  {
    nom: "DUPONT ORTHOPEDIE (GROUPE PROTEOR)",
    adresse: "238 Rue de l'Albeck",
    cp: "59640",
    ville: "Dunkerque",
    departement: "59",
    telephone: "03 28 66 12 89",
    email: "dunkerque@dupontortho.fr",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "PROTEOR STRASBOURG",
    adresse: "2 Rue Paul Rohmer",
    cp: "67200",
    ville: "Strasbourg",
    departement: "67",
    telephone: "07 64 24 29 18",
    email: "strasbourg@proteor.com",
    siteWeb: "http://www.proteor.com",
  },
  {
    nom: "BMO",
    adresse: "2 rue de Dublin",
    cp: "67670",
    ville: "Mommenheim",
    departement: "67",
    telephone: "03 88 80 08 88",
    siteWeb: "https://bmo-prothese-orthese.fr/",
  },
  {
    nom: "SARL ORTHOPEDIA",
    adresse: "Avenue Sampiero Corso RN 193",
    cp: "20600",
    ville: "Bastia",
    departement: "20",
    telephone: "04 95 33 48 12",
  },
  {
    nom: "ORTHESIA ST MARTIN",
    adresse: "108 Howell Center",
    cp: "97150",
    ville: "Saint Martin - Guadeloupe",
    departement: "971",
    telephone: "0590 51 02 79",
    siteWeb: "http://www.orthesia.com/",
  },
  {
    nom: "ORTHO EXPERT (FORMOTION ORTHOPÉDIE)",
    adresse: "Grand Camp La Rocade",
    cp: "97139",
    ville: "Les Abymes - Guadeloupe",
    departement: "971",
    telephone: "(590) 590 95 70 31",
    siteWeb: "https://www.formotion.com/fr-fr",
  },
  {
    nom: "ORTHESIA GUADELOUPE",
    adresse: "8 rue Gaston Dorogant Parc d’activités La Providence ZAC de Dothémare",
    cp: "97139",
    ville: "Les Abymes",
    departement: "971",
    telephone: "0590 90 71 36",
    siteWeb: "http://www.orthesia.com/",
  },
  {
    nom: "ACACIAS ORTHOPEDIE",
    adresse: "Centre Médical Acacias Belcourt 1",
    cp: "97122",
    ville: "Baie Mahault",
    departement: "971",
    telephone: "0590 26 16 26",
  },
  {
    nom: "SOCIETE D'ORTHOPEDIE GUITTEAUD (SOG)",
    adresse: "50 Lot Hibiscus Place d'Armes",
    cp: "97232",
    ville: "Lamentin",
    departement: "972",
    telephone: "0596 51 99 45",
    siteWeb: "http://orthopedieguitteaud.com",
  },
  {
    nom: "ANTILLES ORTHOPEDIE",
    adresse: "8 rue Paulo Rosile Ravine-Vilaine",
    cp: "97200",
    ville: "Fort De France",
    departement: "972",
    telephone: "0596 63 55 50",
    siteWeb: "https://www.antillesorthopedie.fr",
  },
  {
    nom: "ORTHEIS",
    adresse: "3 avenue Eugène Mona",
    cp: "97200",
    ville: "Fort De France",
    departement: "972",
    telephone: "0596 51 09 89",
    siteWeb: "https://www.ortheis.fr",
  },
  {
    nom: "GUYANE ORTHOPROTHESE",
    adresse: "3 place Schoelcher Immeuble Victor Hugo",
    cp: "97300",
    ville: "Cayenne",
    departement: "973",
    telephone: "0594 29 22 37",
    siteWeb: "http://guyaneorthoprothese.com",
  },
  {
    nom: "ORTHO ESPACE 3D",
    adresse: "1 Rue des Arômes",
    cp: "97354",
    ville: "Remire-Montjoly",
    departement: "973",
    telephone: "0594 28 2 8 08",
    email: "contact@orthoespace3d.fr",
    siteWeb: "http://www.orthoespace3d.fr",
  },
  {
    nom: "GUYANE APPAREILLAGE MEDICAL",
    adresse: "660, avenue Justin Catayée",
    cp: "97300",
    ville: "Cayenne",
    departement: "973",
    telephone: "06 94 44 81 16",
    siteWeb: "https://guyane-appareillage-medical.business.site/?utm_source=gmb&utm_medium=referral",
  },
  {
    nom: "TPM MAYOTTE",
    adresse: "16 impasse de l'entrepôt",
    cp: "97600",
    ville: "Mamoudzou",
    departement: "976",
    telephone: "262 639 696 564",
  },
  {
    nom: "NEUT",
    adresse: "129 route Nationale",
    cp: "97660",
    ville: "Nyambadao",
    departement: "976",
    telephone: "",
    email: "info@",
    siteWeb: "http://",
  },
  {
    nom: "RUN ORTHO - ORTHO PEI",
    adresse: "280 rue du Maréchal Leclerc",
    cp: "",
    ville: "Saint Denis",
    departement: "",
    telephone: "+262 0693054715",
    email: "info@",
    siteWeb: "http://www.ortho-pei.com",
  },
  {
    nom: "HTCR",
    adresse: "27 rue du Butor",
    cp: "97400",
    ville: "St Denis De La Reunon",
    departement: "974",
    telephone: "0262 29 81 85",
  },
  {
    nom: "PRO ORTHO",
    adresse: "La mare - Ilot 1 - Atelier 5 1 rue de la pépinière",
    cp: "97438",
    ville: "Sainte Marie",
    departement: "974",
    telephone: "0262 41 24 00",
  },
  {
    nom: "TPM ORTHOPEDIE",
    adresse: "8 rue du cap rond ZI Pierrefonds",
    cp: "97410",
    ville: "Saint-Pierre - Reunion",
    departement: "974",
    telephone: "0262 35 26 26",
  },
]
